Repository PyO3/pyo3, pull requests merged in 2018-11, with the labels that each got.

#260 NonNull pointer for Py, PyObject
  src/instance.rs
  src/object.rs
  src/python.rs
  src/pythonrun.rs
  src/typeob.rs
  src/types/mod.rs
Labels: enhancement

#263 Fix #240
  examples/rustapi_module/tests/test_datetime.py
  src/typeob.rs
Labels: bugfix

#267 Refactor PyObjectAlloc
  pyo3-derive-backend/src/py_class.rs
  src/instance.rs
  src/typeob.rs
  src/types/mod.rs
  src/types/module.rs
Labels: enhancement

#268 Fix PyDictIterator's segfault(for #159)
  examples/rustapi_module/setup.py
  examples/rustapi_module/src/dict_iter.rs
  examples/rustapi_module/src/lib.rs
  examples/rustapi_module/tests/test_dict_iter.py
  src/types/dict.rs
Labels: bugfix

#275 Add clippy to travis
  ci/travis/setup.sh
  ci/travis/test.sh
  src/ffi2/object.rs
  src/ffi2/objimpl.rs
  src/typeob.rs
  src/types/module.rs
  src/types/typeobject.rs
Labels: Continous Integration
