Repository PyO3/pyo3, pull requests merged in 2022-11, with the labels that each got.

#2717 Fix module name in getting started
  guide/src/getting_started.md
Labels: CI-skip-changelog

#2719 push 0.17.3 changelog & package versions to main
  .netlify/_redirects
  CHANGELOG.md
  Cargo.toml
  README.md
  Releasing.md
  examples/Cargo.toml
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/2675.fixed.md
  newsfragments/2676.added.md
  newsfragments/2687.fixed.md
  newsfragments/2708.packaging.md
  pyo3-build-config/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
  pyproject.toml
Labels: CI-skip-changelog

#2721 Update ui tests for Rust 1.65.0
  tests/ui/abi3_nativetype_inheritance.stderr
  tests/ui/invalid_frozen_pyclass_borrow.stderr
  tests/ui/invalid_pymethod_receiver.stderr
  tests/ui/invalid_result_conversion.stderr
  tests/ui/missing_intopy.stderr
  tests/ui/not_send.stderr
  tests/ui/not_send2.stderr
  tests/ui/not_send3.stderr
Labels: CI-skip-changelog

#2720 CI: switch from `actions-rs/toolchain` to `dtolnay/rust-toolchain`
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
Labels: CI-skip-changelog, github-actions

#2712 Also bump CI matrix include jobs to latest stable CPython version.
  .github/workflows/ci.yml
  emscripten/Makefile
  noxfile.py
Labels: CI-skip-changelog

#2740 Make Clippy happy again
  pyo3-ffi/src/cpython/listobject.rs
  pyo3-ffi/src/cpython/tupleobject.rs
  pyo3-ffi/src/objimpl.rs
  src/conversions/chrono.rs
  src/types/datetime.rs
Labels: CI-skip-changelog

#2743 crate doc: add missing links to chrono subpage/crate doc
  src/lib.rs
Labels: CI-skip-changelog

#2744 Replace hidden panics on invalid values passed to chrono by ValueError.
  src/conversions/chrono.rs
Labels: CI-skip-changelog

#2753 CI: fix rayon-core version to keep MSRV compat
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#2752 ffi: link to _PyPyBytes_Resize
  pyo3-ffi/src/cpython/bytesobject.rs
Labels: CI-skip-changelog

#2759 ffi: use bytesobject/dictobject on PyPy
  pyo3-ffi/src/cpython/bytesobject.rs
  pyo3-ffi/src/cpython/dictobject.rs
  pyo3-ffi/src/cpython/mod.rs
Labels: CI-skip-changelog

#2751 guide: better document negative index behavior w.r.t. PySequence
  guide/src/class/protocols.md
Labels: CI-skip-changelog

#2764 guide: linkify "Method arguments" in class.md
  guide/src/class.md
Labels: CI-skip-changelog

#2756 Two smallish cleanups
  src/err/err_state.rs
  src/err/mod.rs
  src/impl_/extract_argument.rs
  src/instance.rs
  src/marker.rs
  src/types/any.rs
  src/types/dict.rs
  src/types/pysuper.rs
  src/types/string.rs
  src/types/typeobject.rs
  tests/test_gc.rs
  tests/test_inheritance.rs
  tests/test_multiple_pymethods.rs
Labels: CI-skip-changelog

#2767 Add link to Python typing docs for type stubs
  guide/src/python_typing_hints.md
Labels: CI-skip-changelog

#2761 ci: configure bors
  .github/bors.toml
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#2762 Add a nox task to rustfmt code in the guide
  guide/pyclass_parameters.md
  guide/src/building_and_distribution.md
  guide/src/building_and_distribution/multiple_python_versions.md
  guide/src/class.md
  guide/src/class/numeric.md
  guide/src/class/object.md
  guide/src/class/protocols.md
  guide/src/conversions/traits.md
  guide/src/ecosystem/async-await.md
  guide/src/exception.md
  guide/src/faq.md
  guide/src/features.md
  guide/src/function.md
  guide/src/function/error_handling.md
  guide/src/function/signature.md
  guide/src/migration.md
  guide/src/parallelism.md
  guide/src/python_from_rust.md
  guide/src/rust_cpython.md
  guide/src/trait_bounds.md
  guide/src/types.md
  noxfile.py
Labels: CI-skip-changelog

#2739 error when `#[pyo3(signature = ())]` used on invalid methods
  guide/src/class/protocols.md
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pyfunction/signature.rs
  pyo3-macros-backend/src/pymethod.rs
  tests/test_compile_error.rs
  tests/ui/invalid_proto_pymethods.rs
  tests/ui/invalid_proto_pymethods.stderr
  tests/ui/invalid_pymethod_proto_args.rs
  tests/ui/invalid_pymethod_proto_args.stderr
  tests/ui/invalid_pymethod_proto_args_py.rs
  tests/ui/invalid_pymethod_proto_args_py.stderr
  tests/ui/invalid_pymethods.rs
  tests/ui/invalid_pymethods.stderr
Labels: CI-skip-changelog

#2763 Typos, grammar, code style, etc.
  guide/src/building_and_distribution.md
  guide/src/class.md
  guide/src/class/numeric.md
  guide/src/debugging.md
  guide/src/ecosystem.md
  guide/src/exception.md
  guide/src/features.md
  guide/src/function/error_handling.md
  guide/src/function/signature.md
  guide/src/getting_started.md
  guide/src/memory.md
  guide/src/migration.md
  guide/src/python_from_rust.md
  guide/src/python_typing_hints.md
  guide/src/rust_cpython.md
  guide/src/types.md
  src/conversions/indexmap.rs
  src/conversions/std/array.rs
  src/conversions/std/num.rs
  src/exceptions.rs
  src/gil.rs
  src/marker.rs
  src/once_cell.rs
  src/pycell.rs
  src/pyclass.rs
  src/types/capsule.rs
  src/types/floatob.rs
  src/types/module.rs
  src/types/pysuper.rs
Labels: CI-skip-changelog

#2779 Mention `into_py` in docs for PyTuple::new
  src/types/tuple.rs
Labels: CI-skip-changelog

#2777 ci: remove `github.sha` from concurrency group
  .github/workflows/ci.yml
Labels: CI, CI-skip-changelog

#2791 netlify: fix mdbook update
  .netlify/build.sh
Labels: CI-skip-changelog
