Repository PyO3/pyo3, pull requests merged in 2023-06, with the labels that each got.

#3199 update PR template to detail state of licensing
  .github/pull_request_template.md
  README.md
Labels: CI-skip-changelog

#3200 RFC: remove copyright headers from source files
  pyo3-macros-backend/src/lib.rs
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pyfunction.rs
  pyo3-macros-backend/src/pyimpl.rs
  pyo3-macros-backend/src/pymethod.rs
  pyo3-macros-backend/src/utils.rs
  pyo3-macros/src/lib.rs
  src/callback.rs
  src/conversion.rs
  src/conversions/num_bigint.rs
  src/derive_utils.rs
  src/err/mod.rs
  src/exceptions.rs
  src/gil.rs
  src/impl_/freelist.rs
  src/instance.rs
  src/marker.rs
  src/prelude.rs
  src/type_object.rs
  src/types/boolobject.rs
  src/types/bytearray.rs
  src/types/capsule.rs
  src/types/code.rs
  src/types/dict.rs
  src/types/floatob.rs
  src/types/frame.rs
  src/types/frozenset.rs
  src/types/iterator.rs
  src/types/list.rs
  src/types/mapping.rs
  src/types/mod.rs
  src/types/module.rs
  src/types/num.rs
  src/types/sequence.rs
  src/types/set.rs
  src/types/slice.rs
  src/types/string.rs
  src/types/traceback.rs
  src/types/tuple.rs
  src/types/typeobject.rs
Labels: CI-skip-changelog

#3210 Drop the xtask helper as it is superseded by Nox.
  .cargo/config
  .netlify/build.sh
  Cargo.toml
  Contributing.md
  noxfile.py
  xtask/Cargo.toml
  xtask/README.md
  xtask/src/cli.rs
  xtask/src/clippy.rs
  xtask/src/doc.rs
  xtask/src/fmt.rs
  xtask/src/main.rs
  xtask/src/pytests.rs
  xtask/src/test.rs
  xtask/src/utils.rs
Labels: CI-skip-changelog

#3211 Enable v2 resolver on the workspace to enable dropping PYO3_CI workaround
  .github/workflows/build.yml
  Cargo.toml
  build.rs
  noxfile.py
Labels: CI-skip-changelog

#3206 add github merge queue support
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#3212 fix usage for paths-filter in merge_group
  .github/workflows/build.yml
Labels: CI-skip-changelog

#3215 Bump Rust edition to 2021 and make current Clippy happy.
  Cargo.toml
  README.md
  examples/Cargo.toml
  examples/decorator/Cargo.toml
  examples/maturin-starter/Cargo.toml
  examples/setuptools-rust-starter/Cargo.toml
  examples/word-count/Cargo.toml
  guide/src/class/numeric.md
  pyo3-build-config/Cargo.toml
  pyo3-ffi-check/Cargo.toml
  pyo3-ffi-check/macro/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-ffi/src/cpython/abstract_.rs
  pyo3-macros-backend/Cargo.toml
  pyo3-macros-backend/src/frompyobject.rs
  pyo3-macros/Cargo.toml
  pytests/Cargo.toml
  pytests/src/pyclasses.rs
  src/lib.rs
  src/pycell.rs
  src/test_hygiene/pyclass.rs
  tests/ui/invalid_closure.stderr
Labels: CI-skip-changelog

#3216 readme: add media June 2023
  README.md
Labels: CI-skip-changelog

#3217 ci: enable full builds with a label
  .github/workflows/ci.yml
Labels: CI-skip-changelog, CI-build-full

#3220 ci: remove bors configuration
  .github/bors.toml
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#3224 ci: pin log for msrv
  noxfile.py
Labels: CI-skip-changelog

#3225 ci: pool can be dirty from other threads
  src/gil.rs
Labels: CI-skip-changelog

#3221 docs: remove unneeded cfg, fixup internal banner
  .netlify/build.sh
  .netlify/internal_banner.html
  noxfile.py
  pyo3-ffi/src/lib.rs
  src/conversion.rs
  src/conversions/anyhow.rs
  src/conversions/chrono.rs
  src/conversions/eyre.rs
  src/conversions/hashbrown.rs
  src/conversions/indexmap.rs
  src/conversions/num_bigint.rs
  src/conversions/num_complex.rs
  src/conversions/rust_decimal.rs
  src/conversions/serde.rs
  src/lib.rs
Labels: CI-skip-changelog

#2709 ci: add Python 3.12-dev jobs
  .github/workflows/build.yml
  .github/workflows/ci.yml
  pyo3-ffi-check/src/main.rs
  pyo3-ffi/src/cpython/code.rs
  pyo3-ffi/src/cpython/compile.rs
  pyo3-ffi/src/cpython/initconfig.rs
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/cpython/pyerrors.rs
  pyo3-ffi/src/cpython/unicodeobject.rs
  pyo3-ffi/src/unicodeobject.rs
  src/ffi/tests.rs
Labels: CI, CI-skip-changelog, CI-build-full

#3227 ci: allow failure on 3.7 and pypy nightly
  .github/workflows/build.yml
Labels: CI-skip-changelog

#3238 add changelog for #3237
  newsfragments/3237.packaging.md
Labels: CI-skip-changelog

#3240 bump maturin version in example files
  examples/decorator/.template/pyproject.toml
  examples/decorator/pyproject.toml
  examples/maturin-starter/.template/pyproject.toml
  examples/maturin-starter/pyproject.toml
  examples/plugin/plugin_api/pyproject.toml
  examples/word-count/pyproject.toml
  guide/src/getting_started.md
  pytests/pyproject.toml
Labels: CI-skip-changelog

#3245 examples: bump edition to 2021
  examples/decorator/.template/Cargo.toml
  examples/maturin-starter/.template/Cargo.toml
  examples/setuptools-rust-starter/.template/Cargo.toml
  examples/word-count/.template/Cargo.toml
Labels: CI-skip-changelog

#3243 Extend guide section on classes regarding free functions
  guide/src/class.md
  guide/src/class/call.md
  guide/src/conversions/traits.md
  guide/src/function.md
  guide/src/function/signature.md
  guide/src/memory.md
  guide/src/migration.md
  guide/src/python_from_rust.md
Labels: CI-skip-changelog

#3249 Improve `PyModule::from_code` examples
  src/types/module.rs
Labels: CI-skip-changelog

#3251 Fix two left-over usages of cfg(addr_of).
  src/pyclass_init.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#3250 Two minor pool optimizations
  src/gil.rs
Labels: CI-skip-changelog

#3255 Replace unreachable! with empty enum match
  pyo3-build-config/src/errors.rs
Labels: CI-skip-changelog

#3254 Remove doctests macro workaround
  src/lib.rs
Labels: CI-skip-changelog

#3260 Give a better error message for Python argument in __traverse__
  pyo3-macros-backend/src/pymethod.rs
  tests/test_compile_error.rs
  tests/ui/traverse.rs
  tests/ui/traverse.stderr
  tests/ui/traverse_bare_self.rs
  tests/ui/traverse_bare_self.stderr
Labels: CI-skip-changelog

#3265 get all badges through shields.io
  README.md
Labels: CI-skip-changelog

#3264 add http headers to help search engines index the docs
  .netlify/build.sh
Labels: CI-skip-changelog

#3274 Our PR template still referenced the removed xtask infrastructure.
  .github/pull_request_template.md
Labels: CI-skip-changelog

#3272 Add conversions between Rust Path/PathBuf and Python str / pathlib.Path
  guide/src/conversions/tables.md
Labels: CI-skip-changelog

#3278 decouple pyo3-ffi-check from MSRV
  .github/workflows/build.yml
  Cargo.toml
  noxfile.py
  pyo3-ffi-check/Cargo.toml
  pyo3-ffi-check/macro/Cargo.toml
  pyo3-ffi-check/src/main.rs
Labels: CI-skip-changelog

#3282 Fix typos and add punctuation recommended by grammarly in Class.md
  guide/src/class.md
Labels: CI-skip-changelog

#3280 clarify ownership of opt_to_pyobj helper function
  src/types/datetime.rs
Labels: CI-skip-changelog
