Repository PyO3/pyo3, pull requests merged in 2023-09, with the labels that each got.

#3414 simplify thread checker implementation
  guide/src/class.md
  pyo3-macros-backend/src/pyclass.rs
  src/impl_/pyclass.rs
  src/types/mod.rs
  tests/test_class_basics.rs
  tests/ui/abi3_nativetype_inheritance.stderr
  tests/ui/pyclass_send.stderr
Labels: CI-skip-changelog

#3433 Add `noplayground` annotation to guide snippets
  guide/book.toml
Labels: CI-skip-changelog

#3436 add comments to ffi def structures
  pyo3-ffi/src/descrobject.rs
  pyo3-ffi/src/methodobject.rs
Labels: CI-skip-changelog

#3441 remove some redundant explicit doc links
  pyo3-build-config/src/impl_.rs
  src/types/floatob.rs
  src/types/module.rs
Labels: CI-skip-changelog

#3434 add --no-fail-fast to cargo test in CI
  noxfile.py
Labels: CI-skip-changelog

#3444 Fix name of `_Py_LocalMonitors` in latest 3.12 RCs
  pyo3-ffi/src/cpython/code.rs
Labels: CI-skip-changelog

#3404 call PyObject_GC_Untrack before deallocating
  .github/workflows/ci.yml
  guide/src/class.md
  newsfragments/3404.fixed.md
  noxfile.py
  pyo3-ffi/src/objimpl.rs
  pyo3-macros-backend/src/pyclass.rs
  src/impl_/freelist.rs
  src/impl_/pyclass.rs
  src/pycell.rs
  src/pycell/impl_.rs
  src/pyclass.rs
  src/pyclass/create_type_object.rs
Labels: CI-no-fail-fast, CI-build-full

#3450 add pyo3-runtime stub package
  pyo3-runtime/LICENSE-APACHE
  pyo3-runtime/LICENSE-MIT
  pyo3-runtime/README.md
  pyo3-runtime/pyproject.toml
  pyo3-runtime/src/pyo3_runtime/__init__.py
  pyo3-runtime/tests/__init__.py
Labels: CI-skip-changelog

#3462 ci: adjust tests to avoid chrono panics
  src/conversions/chrono.rs
Labels: CI-skip-changelog

#3465 Fix a typo in a documentation page title
  guide/src/python_typing_hints.md
Labels: CI-skip-changelog

#3459 fix codecov ignore paths for test folders
  codecov.yml
Labels: CI-skip-changelog

#3472 unify 3.12 / non-3.12 error handling branches
  src/err/err_state.rs
  src/err/mod.rs
Labels: CI-skip-changelog

#3469 refactor chrono implementation to be more DRY
  src/conversions/chrono.rs
Labels: CI-skip-changelog

#3470 add `assert_warnings` test helper
  src/err/mod.rs
  src/lib.rs
  src/tests/common.rs
  src/tests/hygiene/misc.rs
  src/tests/hygiene/mod.rs
  src/tests/hygiene/pyclass.rs
  src/tests/hygiene/pyfunction.rs
  src/tests/hygiene/pymethods.rs
  src/tests/hygiene/pymodule.rs
  src/tests/mod.rs
  tests/common.rs
  tests/test_arithmetics.rs
  tests/test_buffer.rs
  tests/test_buffer_protocol.rs
  tests/test_bytes.rs
  tests/test_class_attributes.rs
  tests/test_class_basics.rs
  tests/test_class_conversion.rs
  tests/test_default_impls.rs
  tests/test_enum.rs
  tests/test_exceptions.rs
  tests/test_frompyobject.rs
  tests/test_gc.rs
  tests/test_getter_setter.rs
  tests/test_inheritance.rs
  tests/test_macro_docs.rs
  tests/test_macros.rs
  tests/test_mapping.rs
  tests/test_methods.rs
  tests/test_module.rs
  tests/test_multiple_pymethods.rs
  tests/test_proto_methods.rs
  tests/test_pyfunction.rs
  tests/test_pyself.rs
  tests/test_sequence.rs
  tests/test_static_slots.rs
  tests/test_string.rs
  tests/test_text_signature.rs
  tests/test_variable_arguments.rs
  tests/test_various.rs
Labels: CI-skip-changelog

#3476 remove branches for dead `call` and `init` attrs
  pyo3-macros-backend/src/method.rs
Labels: CI-skip-changelog

#3471 always normalize exceptions before raising
  newsfragments/3471.fixed.md
  pytests/requirements-dev.txt
  pytests/src/awaitable.rs
  pytests/src/lib.rs
  pytests/tests/test_awaitable.py
  src/err/err_state.rs
Labels: CI-build-full

#3478 Don't let auto trait syntax bleed through on stable Rust
  src/marker.rs
Labels: CI-skip-changelog, CI-build-full

#3446 relax multiple-import check to only prevent subinterpreters
  guide/src/building_and_distribution.md
  newsfragments/3446.changed.md
  pytests/tests/test_misc.py
  src/impl_/pymodule.rs
Labels: CI-build-full
