Repository PyO3/pyo3, pull requests merged in 2023-07, with the labels that each got.

#3290 update main for 0.19.1
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/Cargo.toml
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/3156.added.md
  newsfragments/3185.fixed.md
  newsfragments/3197.added.md
  newsfragments/3198.added.md
  newsfragments/3248.added.md
  newsfragments/3258.packaging.md
  newsfragments/3263.added.md
  newsfragments/3270.added.md
  newsfragments/3271.fixed.md
  newsfragments/3277.packaging.md
  newsfragments/3286.fixed.md
  newsfragments/3287.added.md
  newsfragments/3289.packaging.md
  pyo3-build-config/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
  pyproject.toml
Labels: CI-skip-changelog

#3292 ci: run valgrind and careful with 'CI-build-full' label
  .github/workflows/ci.yml
Labels: CI-skip-changelog, CI-build-full

#3293 add some missing type conversions to the guide
  guide/src/conversions/tables.md
Labels: CI-skip-changelog

#3273 add some style guide to Contributing.md
  Contributing.md
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/pymethod.rs
  src/buffer.rs
  src/conversions/std/num.rs
  src/conversions/std/osstr.rs
  src/err/mod.rs
  src/ffi/tests.rs
  src/impl_/extract_argument.rs
  src/impl_/pyclass/lazy_type_object.rs
  src/impl_/pyfunction.rs
  src/impl_/pymethods.rs
  src/impl_/trampoline.rs
  src/instance.rs
  src/macros.rs
  src/marker.rs
  src/pyclass/create_type_object.rs
  src/types/any.rs
  src/types/dict.rs
  src/types/frozenset.rs
  src/types/list.rs
  src/types/mapping.rs
  src/types/sequence.rs
  src/types/set.rs
  tests/ui/traverse.stderr
Labels: CI-skip-changelog

#3303 RFC: Add implementation of Iterator::size_hint for PyIterator
  benches/bench_any.rs
  pyo3-ffi/src/boolobject.rs
  pyo3-macros-backend/src/attributes.rs
  src/impl_/pyclass.rs
  src/types/iterator.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#3307 Resolve nightly clippy warning in test_field_cfg
  tests/test_field_cfg.rs
Labels: CI-skip-changelog

#3309 remove some dead fields from FnArg
  pyo3-macros-backend/src/method.rs
Labels: CI-skip-changelog

#3311 improve error span for mutable access to `#[pyclass(frozen)]`
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  tests/ui/invalid_frozen_pyclass_borrow.rs
  tests/ui/invalid_frozen_pyclass_borrow.stderr
Labels: CI-skip-changelog

#3314 Tiny grammar fix in error_handling.md
  guide/src/function/error_handling.md
Labels: CI-skip-changelog

#3315 codecov: ignore coverage for pytests directory
  codecov.yml
Labels: CI-skip-changelog

#3317 ci: updates for rust 1.71
  benches/bench_dict.rs
  benches/bench_list.rs
  benches/bench_set.rs
  benches/bench_tuple.rs
  pyo3-macros-backend/src/pyimpl.rs
  pyo3-macros-backend/src/utils.rs
  pytests/src/dict_iter.rs
  src/conversions/hashbrown.rs
  src/conversions/indexmap.rs
  src/conversions/std/map.rs
  src/exceptions.rs
  src/types/dict.rs
  src/types/frozenset.rs
  src/types/list.rs
  src/types/sequence.rs
  src/types/set.rs
  src/types/string.rs
  tests/test_dict_iter.rs
  tests/ui/invalid_closure.stderr
  tests/ui/invalid_frozen_pyclass_borrow.stderr
  tests/ui/not_send.stderr
  tests/ui/not_send2.stderr
Labels: CI-skip-changelog

#3320 Update outdated link in python_typing_hints.md and fix typos
  guide/src/python_typing_hints.md
Labels: CI-skip-changelog

#3312 optimize is_instance for PyBaseException
  src/err/mod.rs
  src/exceptions.rs
Labels: CI-skip-changelog

#3318 macros: change self_arg to be an expression
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pymethod.rs
Labels: CI-skip-changelog

#3321 collect arrays of objects prior to filling tuple in fixed-size conversions
  benches/bench_tuple.rs
  newsfragments/3321.changed.md
  src/types/tuple.rs
Labels: CI-skip-changelog

#3322 Add tzfpy
  README.md
Labels: CI-skip-changelog

#3319 clippy: deny / fix used-underscope-binding lint
  .cargo/config
  pyo3-ffi/src/cpython/abstract_.rs
  pyo3-ffi/src/cpython/unicodeobject.rs
  pyo3-macros-backend/src/method.rs
  src/pyclass/gc.rs
  tests/test_class_new.rs
  tests/test_pep_587.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#3323 merge PyErr internal states for simplicity
  src/err/err_state.rs
  src/err/mod.rs
Labels: CI-skip-changelog

#3331 Install wheel for the setuptools-rust-starter example
  examples/setuptools-rust-starter/requirements-dev.txt
Labels: CI-skip-changelog

#3332 add 3.12 and PyPy 3.10 to clippy jobs
  noxfile.py
Labels: CI-skip-changelog

#3337 Add haem to example projects
  README.md
Labels: CI-skip-changelog

#3338 ci: avoid failure to build numpy on 3.12
  pytests/noxfile.py
  pytests/tests/test_sequence.py
Labels: CI-skip-changelog

#3342 fix ffi check failures for 3.12.0b4
  .github/workflows/build.yml
  newsfragments/3342.changed.md
  pyo3-ffi-check/macro/Cargo.toml
  pyo3-ffi-check/macro/src/lib.rs
  pyo3-ffi-check/src/main.rs
  pyo3-ffi/src/cpython/code.rs
  pyo3-ffi/src/cpython/funcobject.rs
  pyo3-ffi/src/cpython/genobject.rs
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/cpython/unicodeobject.rs
Labels: CI-no-fail-fast, CI-build-full

#3343 ci: stop allowing failure for pypy 3.10
  .github/workflows/build.yml
Labels: CI-skip-changelog

#3347 fix compile failure for getter with return lifetime of self
  pyo3-macros-backend/src/lib.rs
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  pyo3-macros-backend/src/quotes.rs
  tests/test_getter_setter.rs
Labels: CI-skip-changelog

#3355 decouple benchmarks from msrv
  .github/workflows/gh-pages.yml
  Cargo.toml
  Contributing.md
  noxfile.py
  pyo3-benches/Cargo.toml
  pyo3-benches/benches/bench_any.rs
  pyo3-benches/benches/bench_call.rs
  pyo3-benches/benches/bench_comparisons.rs
  pyo3-benches/benches/bench_decimal.rs
  pyo3-benches/benches/bench_dict.rs
  pyo3-benches/benches/bench_err.rs
  pyo3-benches/benches/bench_extract.rs
  pyo3-benches/benches/bench_frompyobject.rs
  pyo3-benches/benches/bench_gil.rs
  pyo3-benches/benches/bench_intern.rs
  pyo3-benches/benches/bench_list.rs
  pyo3-benches/benches/bench_pyclass.rs
  pyo3-benches/benches/bench_pyobject.rs
  pyo3-benches/benches/bench_set.rs
  pyo3-benches/benches/bench_tuple.rs
Labels: CI-skip-changelog

#3335 update object.h definitions for Python 3.12
  newsfragments/3335.changed.md
  newsfragments/3335.fixed.md
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/lib.rs
  pyo3-ffi/src/object.rs
  pyo3-ffi/src/pybuffer.rs
  pyo3-ffi/src/pyport.rs
  src/ffi/mod.rs
  src/ffi/tests.rs
  src/types/dict.rs
  src/types/iterator.rs
  src/types/list.rs
Labels: CI-no-fail-fast, CI-build-full
