Repository PyO3/pyo3, pull requests merged in 2024-02, with the labels that each got.

#3777 add `PyBytes::new_bound`
  guide/src/conversions/traits.md
  pytests/src/buf_and_str.rs
  src/conversions/anyhow.rs
  src/conversions/eyre.rs
  src/conversions/num_bigint.rs
  src/conversions/std/slice.rs
  src/tests/hygiene/pymethods.rs
  src/types/bytes.rs
  tests/test_bytes.rs
Labels: CI-skip-changelog

#3785 add `Bound::as_any` and `Bound::into_any` (and same for `Py`)
  newsfragments/3785.added.md
  src/instance.rs
Labels: CI-skip-changelog

#3790 add `Bound` constructor for `PyBool`
  guide/src/exception.md
  src/impl_/pyclass.rs
  src/instance.rs
  src/types/any.rs
  src/types/boolobject.rs
  tests/test_class_attributes.rs
Labels: CI-skip-changelog

#3794 Revert "Merge pull request #3578 from davidhewitt/typed-helpers"
  guide/src/class/protocols.md
  guide/src/migration.md
  newsfragments/3578.changed.md
  pyo3-benches/benches/bench_gil.rs
  pyo3-benches/benches/bench_pyobject.rs
  pyo3-macros-backend/src/pyclass.rs
  pytests/src/awaitable.rs
  src/conversion.rs
  src/conversions/chrono.rs
  src/err/mod.rs
  src/ffi/tests.rs
  src/marker.rs
  src/types/bytearray.rs
  tests/test_arithmetics.rs
  tests/test_class_conversion.rs
  tests/test_exceptions.rs
  tests/test_frompyobject.rs
  tests/test_gc.rs
  tests/test_no_imports.rs
Labels: CI-skip-changelog

#3793 Implement new API for PyNone #3684
  src/coroutine.rs
  src/marker.rs
  src/types/none.rs
Labels: CI-skip-changelog

#3796 convert `marshal` to `Bound` API
  src/marshal.rs
Labels: CI-skip-changelog

#3797 PyEllipsis and PyNotImplemented new get_bound api
  src/marker.rs
  src/types/ellipsis.rs
  src/types/none.rs
  src/types/notimplemented.rs
Labels: CI-skip-changelog

#3798 ci: fix beta clippy `map_clone` warning
  src/instance.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#3799 move `Cow[u8]` conversions into `conversions::std::slice` module
  src/conversions/std/slice.rs
  src/types/bytes.rs
Labels: CI-skip-changelog

#3792 pyclass methods for `Bound`
  src/instance.rs
Labels: CI-skip-changelog

#3779 expose `Bound::from_owned_ptr` etc
  src/instance.rs
Labels: CI-skip-changelog

#3800 PyCFunction bound api
  src/impl_/pyfunction.rs
  src/types/function.rs
  tests/test_pyfunction.rs
  tests/ui/invalid_closure.rs
  tests/ui/invalid_closure.stderr
Labels: CI-skip-changelog

#3813 ci: allow some dead code warnings on nightly
  guide/src/trait_bounds.md
  src/marker.rs
  tests/ui/not_send.stderr
  tests/ui/not_send2.stderr
  tests/ui/traverse.stderr
Labels: CI-skip-changelog

#3806 port `Python::eval` to `Bound` API
  README.md
  guide/src/conversions/traits.md
  guide/src/memory.md
  guide/src/migration.md
  guide/src/python_from_rust.md
  src/buffer.rs
  src/conversions/chrono.rs
  src/conversions/num_bigint.rs
  src/conversions/std/array.rs
  src/conversions/std/num.rs
  src/conversions/std/slice.rs
  src/exceptions.rs
  src/ffi/tests.rs
  src/gil.rs
  src/lib.rs
  src/marker.rs
  src/types/iterator.rs
  src/types/mod.rs
  tests/test_datetime.rs
  tests/test_frompyobject.rs
  tests/test_inheritance.rs
Labels: CI-skip-changelog

#3816 port `Python::run` to `Bound` API
  guide/src/class/numeric.md
  guide/src/module.md
  guide/src/python_from_rust.md
  src/conversions/anyhow.rs
  src/conversions/chrono.rs
  src/conversions/eyre.rs
  src/conversions/rust_decimal.rs
  src/conversions/std/num.rs
  src/err/mod.rs
  src/exceptions.rs
  src/ffi/tests.rs
  src/gil.rs
  src/macros.rs
  src/marker.rs
  src/tests/common.rs
  src/types/bytearray.rs
  src/types/traceback.rs
  tests/test_anyhow.rs
  tests/test_append_to_inittab.rs
  tests/test_class_new.rs
  tests/test_coroutine.rs
  tests/test_datetime.rs
  tests/test_gc.rs
  tests/test_inheritance.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#3817 port `IntoPyDict` to `Bound` API
  README.md
  guide/src/exception.md
  guide/src/migration.md
  guide/src/module.md
  guide/src/python_from_rust.md
  src/conversions/anyhow.rs
  src/conversions/chrono.rs
  src/conversions/eyre.rs
  src/conversions/hashbrown.rs
  src/conversions/indexmap.rs
  src/conversions/std/map.rs
  src/exceptions.rs
  src/impl_/extract_argument.rs
  src/instance.rs
  src/lib.rs
  src/macros.rs
  src/marker.rs
  src/tests/common.rs
  src/types/any.rs
  src/types/dict.rs
  tests/test_buffer_protocol.rs
  tests/test_class_new.rs
  tests/test_coroutine.rs
  tests/test_datetime.rs
  tests/test_dict_iter.rs
  tests/test_getter_setter.rs
  tests/test_inheritance.rs
  tests/test_macro_docs.rs
  tests/test_mapping.rs
  tests/test_methods.rs
  tests/test_module.rs
  tests/test_no_imports.rs
  tests/test_sequence.rs
  tests/test_static_slots.rs
Labels: CI-skip-changelog

#3819 Implement PyErr::get_type_bound
  guide/src/python_from_rust.md
  src/err/err_state.rs
  src/err/mod.rs
  src/impl_/extract_argument.rs
Labels: CI-skip-changelog

#3823 deprecate `PyDict::new` constructor
  guide/src/conversions/traits.md
  pyo3-benches/benches/bench_any.rs
  pyo3-benches/benches/bench_bigint.rs
  pyo3-benches/benches/bench_decimal.rs
  pyo3-benches/benches/bench_dict.rs
  pyo3-benches/benches/bench_extract.rs
  src/conversions/num_bigint.rs
  src/conversions/smallvec.rs
  src/conversions/std/time.rs
  src/impl_/extract_argument.rs
  src/instance.rs
  src/marshal.rs
  src/sync.rs
  src/types/any.rs
  src/types/dict.rs
  src/types/ellipsis.rs
  src/types/none.rs
  src/types/notimplemented.rs
  tests/test_frompyobject.rs
  tests/test_proto_methods.rs
  tests/ui/wrong_aspyref_lifetimes.rs
  tests/ui/wrong_aspyref_lifetimes.stderr
Labels: CI-skip-changelog

#3826 Pyerr isinstance
  src/err/mod.rs
Labels: CI-skip-changelog

#3829 add `DowncastIntoError::into_inner`
  src/err/mod.rs
  src/types/any.rs
Labels: CI-skip-changelog

#3828 update `#[derive(FromPyObject)]` to use `extract_bound`
  pyo3-macros-backend/src/frompyobject.rs
  src/impl_/frompyobject.rs
  tests/test_frompyobject.rs
Labels: CI-skip-changelog

#3830 ci: don't test gevent on pypy
  pytests/pyproject.toml
  pytests/tests/test_misc.py
Labels: CI-skip-changelog

#3821 add maximum Python version check
  .github/workflows/ci.yml
  Cargo.toml
  newsfragments/3821.packaging.md
  noxfile.py
  pyo3-build-config/src/impl_.rs
  pyo3-ffi/build.rs
  pyo3-macros-backend/Cargo.toml
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/utils.rs
  pyo3-macros/Cargo.toml
Labels: CI-build-full

#3832 port `Python::import` to `Bound` API
  README.md
  guide/src/python_from_rust.md
  src/buffer.rs
  src/conversions/chrono.rs
  src/conversions/chrono_tz.rs
  src/conversions/rust_decimal.rs
  src/conversions/std/time.rs
  src/coroutine/waker.rs
  src/err/mod.rs
  src/exceptions.rs
  src/gil.rs
  src/impl_/pymodule.rs
  src/instance.rs
  src/lib.rs
  src/marker.rs
  src/sync.rs
  src/tests/common.rs
  src/types/any.rs
  src/types/traceback.rs
  tests/test_class_attributes.rs
  tests/test_coroutine.rs
  tests/test_datetime.rs
  tests/test_datetime_import.rs
  tests/test_various.rs
  tests/ui/invalid_intern_arg.rs
  tests/ui/invalid_intern_arg.stderr
Labels: CI-skip-changelog

#3837 allow `from_py_with` on function args to take a `fn(&Bound) -> PyResult`
  pyo3-macros-backend/src/params.rs
  src/impl_/extract_argument.rs
  src/impl_/frompyobject.rs
Labels: CI-skip-changelog

#3836 convert `PyBuffer` to `Bound` API
  pytests/src/buf_and_str.rs
  src/buffer.rs
  tests/test_buffer.rs
  tests/test_buffer_protocol.rs
Labels: CI-skip-changelog

#3802 add `PyBackedStr` and `PyBackedBytes`
  newsfragments/3802.added.md
  src/lib.rs
  src/pybacked.rs
Labels: CI-build-full

#3842 port `PyErr::warn` to `Bound` API
  src/conversions/chrono.rs
  src/err/mod.rs
  src/exceptions.rs
Labels: CI-skip-changelog

#3831 support `Bound` for `classmethod` and `pass_module`
  guide/src/class.md
  guide/src/function.md
  pyo3-macros-backend/src/method.rs
  pytests/src/pyclasses.rs
  pytests/tests/test_pyclasses.py
  src/impl_/pymethods.rs
  src/instance.rs
  src/tests/hygiene/pymethods.rs
  tests/test_class_basics.rs
  tests/test_methods.rs
  tests/test_module.rs
  tests/test_multiple_pymethods.rs
  tests/test_no_imports.rs
  tests/test_text_signature.rs
  tests/ui/invalid_pyfunctions.stderr
  tests/ui/invalid_pymethods.stderr
Labels: CI-skip-changelog

#3845 docs: fix link in Contributing.md
  Contributing.md
Labels: CI-skip-changelog

#3820 Pyerr value bound
  guide/src/python_from_rust.md
  src/conversions/anyhow.rs
  src/conversions/chrono.rs
  src/conversions/eyre.rs
  src/coroutine.rs
  src/err/err_state.rs
  src/err/impls.rs
  src/err/mod.rs
  src/exceptions.rs
  src/impl_/extract_argument.rs
  src/tests/common.rs
  src/types/string.rs
  src/types/traceback.rs
  tests/test_coroutine.rs
Labels: CI-skip-changelog

#3850 port `PyFrozenSetBuilder` to `Bound` API
  src/types/frozenset.rs
Labels: CI-skip-changelog

#3851 deprecate `PyFrozenSet::empty`
  src/types/frozenset.rs
Labels: CI-skip-changelog

#3852 Remove stray " character from docstring
  src/instance.rs
Labels: CI-skip-changelog

#3853 Use the new bound API instead of .as_ref(py)
  src/conversions/std/ipaddr.rs
  src/conversions/std/osstr.rs
  src/conversions/std/slice.rs
  src/conversions/std/string.rs
  src/coroutine.rs
  src/coroutine/cancel.rs
  src/coroutine/waker.rs
  src/err/mod.rs
  src/instance.rs
  src/pycell.rs
  src/types/capsule.rs
  tests/test_class_basics.rs
  tests/test_class_conversion.rs
  tests/test_field_cfg.rs
  tests/test_inheritance.rs
  tests/test_mapping.rs
  tests/test_proto_methods.rs
  tests/test_pyself.rs
  tests/test_sequence.rs
  tests/test_various.rs
Labels: CI-skip-changelog

#3856 port `PyObject::downcast` to `Bound` API
  src/conversions/hashbrown.rs
  src/conversions/indexmap.rs
  src/conversions/std/array.rs
  src/conversions/std/map.rs
  src/err/mod.rs
  src/instance.rs
  src/marker.rs
  src/types/mapping.rs
  src/types/none.rs
  src/types/tuple.rs
Labels: CI-skip-changelog

#3705 implement `PyTypeMethods`
  src/err/err_state.rs
  src/err/mod.rs
  src/instance.rs
  src/prelude.rs
  src/types/any.rs
  src/types/boolobject.rs
  src/types/mod.rs
  src/types/typeobject.rs
  tests/test_class_basics.rs
Labels: CI-skip-changelog

#3846 port `Python::get_type` to `Bound` API
  guide/src/class.md
  guide/src/exception.md
  pyo3-macros-backend/src/pyclass.rs
  src/conversions/chrono.rs
  src/conversions/num_bigint.rs
  src/err/mod.rs
  src/exceptions.rs
  src/impl_/extract_argument.rs
  src/macros.rs
  src/marker.rs
  src/pyclass_init.rs
  src/tests/common.rs
  src/types/typeobject.rs
  tests/test_class_attributes.rs
  tests/test_class_basics.rs
  tests/test_class_new.rs
  tests/test_coroutine.rs
  tests/test_enum.rs
  tests/test_gc.rs
  tests/test_getter_setter.rs
  tests/test_inheritance.rs
  tests/test_macro_docs.rs
  tests/test_macros.rs
  tests/test_mapping.rs
  tests/test_methods.rs
  tests/test_multiple_pymethods.rs
  tests/test_no_imports.rs
  tests/test_proto_methods.rs
  tests/test_sequence.rs
  tests/test_static_slots.rs
  tests/test_super.rs
  tests/test_text_signature.rs
  tests/test_variable_arguments.rs
Labels: CI-skip-changelog

#3855 Convert LazyTypeObject to use the Bound API
  pyo3-macros-backend/src/pyclass.rs
  src/impl_/pyclass/lazy_type_object.rs
Labels: CI-skip-changelog

#3858 add Bound API constructors from borrowed pointers
  src/instance.rs
Labels: CI-skip-changelog

#3866 port `PyComplex::from_complex` to `Bound` API
  src/conversions/num_complex.rs
  src/prelude.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#3873 ci: fix redundant import warnings on nightly
  guide/src/class/numeric.md
  guide/src/python_from_rust.md
  pyo3-build-config/src/impl_.rs
  src/conversions/chrono.rs
  src/conversions/hashbrown.rs
  src/conversions/num_bigint.rs
  src/conversions/rust_decimal.rs
  src/conversions/smallvec.rs
  src/conversions/std/map.rs
  src/conversions/std/num.rs
  src/exceptions.rs
  src/marker.rs
  src/pyclass/create_type_object.rs
  src/sync.rs
  src/types/capsule.rs
  src/types/dict.rs
  src/types/function.rs
  src/types/list.rs
  src/types/mapping.rs
  src/types/string.rs
  src/types/traceback.rs
  src/types/tuple.rs
  tests/test_class_conversion.rs
  tests/test_exceptions.rs
  tests/test_gc.rs
  tests/test_inheritance.rs
  tests/test_methods.rs
  tests/test_proto_methods.rs
  tests/test_pyself.rs
  tests/test_text_signature.rs
  tests/test_various.rs
Labels: CI-skip-changelog, CI-build-full

#3874 ci: cancel in-progress benches job on push
  .github/workflows/benches.yml
Labels: CI-skip-changelog

#3869 migrate some final `FromPyObject` implementations to the `Bound` API
  src/conversion.rs
  src/conversions/std/cell.rs
  src/conversions/std/mod.rs
  src/conversions/std/option.rs
  src/instance.rs
Labels: CI-skip-changelog

#3868 update `py.import` -> `py.import_bound` in benches
  pyo3-benches/benches/bench_intern.rs
Labels: CI-skip-changelog

#3863 Replace as_ref(py) with Bound APIs
  src/err/mod.rs
  src/pyclass/create_type_object.rs
  tests/test_methods.rs
Labels: CI-skip-changelog

#3861 ci: disable some benchmarks volatile on codspeed
  pyo3-benches/benches/bench_dict.rs
  pyo3-benches/benches/bench_extract.rs
  pyo3-benches/benches/bench_frompyobject.rs
  pyo3-benches/benches/bench_list.rs
  pyo3-benches/benches/bench_tuple.rs
Labels: CI-skip-changelog

#3867 Deprecate Py::into_ref
  guide/src/types.md
  src/conversions/chrono.rs
  src/exceptions.rs
  src/impl_/pymodule.rs
  src/instance.rs
  src/marker.rs
  src/types/any.rs
  src/types/traceback.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#3872 deprecate `PyCell::new` in favor of `Py::new` or `Bound::new`
  guide/src/class.md
  guide/src/class/object.md
  guide/src/class/protocols.md
  guide/src/migration.md
  guide/src/python_from_rust.md
  guide/src/types.md
  src/macros.rs
  src/pycell.rs
  tests/test_arithmetics.rs
  tests/test_class_basics.rs
  tests/test_class_conversion.rs
  tests/test_class_new.rs
  tests/test_gc.rs
  tests/test_inheritance.rs
  tests/test_methods.rs
  tests/test_proto_methods.rs
  tests/test_pyself.rs
  tests/test_sequence.rs
  tests/test_various.rs
Labels: CI-skip-changelog

#3875 Deprecate `py.from_owned_ptr` methods
  src/conversion.rs
  src/exceptions.rs
  src/ffi/tests.rs
  src/instance.rs
  src/marker.rs
  src/pycell.rs
  src/types/bytearray.rs
  src/types/complex.rs
  src/types/memoryview.rs
  src/types/module.rs
  src/types/slice.rs
  src/types/string.rs
Labels: CI-skip-changelog

#3834 fix `either` feature conditional compilation, again
  .github/workflows/ci.yml
  Cargo.toml
  newsfragments/3834.fixed.md
  noxfile.py
  pytests/src/comparisons.rs
  src/conversions/either.rs
Labels: CI-build-full

#3775 add `PyModule::new_bound` and `PyModule::import_bound`
  examples/maturin-starter/src/lib.rs
  examples/plugin/src/main.rs
  examples/setuptools-rust-starter/src/lib.rs
  guide/src/class.md
  guide/src/class/numeric.md
  guide/src/conversions/traits.md
  guide/src/function/signature.md
  guide/src/module.md
  guide/src/python_from_rust.md
  pyo3-benches/benches/bench_call.rs
  pyo3-benches/benches/bench_intern.rs
  pytests/src/lib.rs
  src/conversions/anyhow.rs
  src/conversions/chrono.rs
  src/conversions/chrono_tz.rs
  src/conversions/eyre.rs
  src/conversions/num_bigint.rs
  src/conversions/num_complex.rs
  src/instance.rs
  src/marker.rs
  src/pyclass_init.rs
  src/types/any.rs
  src/types/capsule.rs
  src/types/module.rs
  src/types/traceback.rs
  tests/test_class_basics.rs
  tests/test_class_new.rs
  tests/test_coroutine.rs
  tests/test_inheritance.rs
  tests/test_module.rs
  tests/test_proto_methods.rs
  tests/test_various.rs
Labels: CI-skip-changelog

#3879 fix `AsRef` and `Deref` impls on `Bound<T>`
  guide/src/class/object.md
  pyo3-macros-backend/src/pyclass.rs
  src/instance.rs
  src/types/boolobject.rs
  src/types/mod.rs
  tests/test_buffer.rs
  tests/test_class_conversion.rs
  tests/test_field_cfg.rs
  tests/test_inheritance.rs
  tests/test_mapping.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#3884 add missing deprecation for `PyDict::from_sequence`
  src/types/dict.rs
Labels: CI-skip-changelog

#3877 Tidy some usage of `py.from_borrowed_ptr` and `py.from_borrowed_ptr_or_opt`
  pyo3-macros-backend/src/pymethod.rs
  src/ffi/tests.rs
  src/impl_/pyclass.rs
  src/impl_/pymethods.rs
  src/instance.rs
Labels: CI-skip-changelog

#3885 port `PyErr::from_type` to `Bound` API
  src/err/mod.rs
Labels: CI-skip-changelog

#3890 release: 0.20.3
  CHANGELOG.md
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/3619.fixed.md
  newsfragments/3821.packaging.md
  newsfragments/3834.fixed.md
Labels: CI-skip-changelog

#3889 macros: exact dependency on `pyo3-build-config`
  pyo3-macros-backend/Cargo.toml
Labels: CI-skip-changelog

#3883 Update new_closure_bound closure signature
  src/types/function.rs
  tests/test_pyfunction.rs
  tests/ui/invalid_closure.rs
  tests/ui/invalid_closure.stderr
Labels: CI-skip-changelog

#3893 Tidy up deprecation message on bound api
  src/conversion.rs
  src/instance.rs
  src/marker.rs
  src/pycell.rs
Labels: CI-skip-changelog

#3895 reexport `PyAnyMethods` and friends from `pyo3::types`
  src/conversions/indexmap.rs
  src/prelude.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#3892 move chat discussions to Discord
  .github/ISSUE_TEMPLATE/config.yml
  Contributing.md
  README.md
  guide/src/faq.md
  guide/src/getting_started.md
Labels: CI-skip-changelog

#3896 allow `Bound<'_, T>` in #[pymethods] `self` position
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pyclass.rs
  src/impl_/pymethods.rs
  src/pycell.rs
  tests/ui/invalid_pymethod_receiver.stderr
Labels: CI-skip-changelog

#3898 ci: apply correct permissions for cache cleanup job
  .github/workflows/cache-cleanup.yml
Labels: CI-skip-changelog

#3887 ci: move cross compile tests to their own jobs
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#3881 Implement `From<Bound<'py, T>>` for PyErr
  src/err/mod.rs
  src/exceptions.rs
  src/lib.rs
  src/types/string.rs
  tests/ui/invalid_result_conversion.stderr
Labels: CI-skip-changelog

#3860 store `Bound<T>` inside `PyRef` and `PyRefMut`
  src/conversion.rs
  src/impl_/pymethods.rs
  src/instance.rs
  src/pycell.rs
Labels: CI-skip-changelog

#3897 Pymodule bound
  guide/src/module.md
  guide/src/python_from_rust.md
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/pyfunction.rs
  src/impl_/pyfunction.rs
  src/macros.rs
  src/prelude.rs
  src/types/function.rs
  src/types/module.rs
  tests/test_module.rs
  tests/test_pyfunction.rs
  tests/test_wrap_pyfunction_deduction.rs
Labels: CI-skip-changelog

#3910 cleans up `PyCFunction::internal_new`
  pyo3-macros-backend/src/pyfunction.rs
  src/impl_/pyfunction.rs
  src/types/function.rs
Labels: CI-skip-changelog

#3708 update `extract_argument` to use Bound APIs
  guide/src/class.md
  pyo3-benches/benches/bench_comparisons.rs
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  pytests/src/pyfunctions.rs
  src/impl_/extract_argument.rs
  src/impl_/pymethods.rs
  src/types/dict.rs
  src/types/string.rs
  src/types/tuple.rs
Labels: CI-skip-changelog

#3909 seals `PyAnyMethods` and friends
  src/ffi_ptr_ext.rs
  src/lib.rs
  src/py_result_ext.rs
  src/sealed.rs
  src/types/any.rs
  src/types/boolobject.rs
  src/types/bytearray.rs
  src/types/bytes.rs
  src/types/capsule.rs
  src/types/complex.rs
  src/types/dict.rs
  src/types/float.rs
  src/types/frozenset.rs
  src/types/list.rs
  src/types/mapping.rs
  src/types/module.rs
  src/types/sequence.rs
  src/types/set.rs
  src/types/slice.rs
  src/types/string.rs
  src/types/traceback.rs
  src/types/tuple.rs
  src/types/typeobject.rs
Labels: CI-skip-changelog

#3899 Use single-arg form of `#[pymodule]` function in docs and tests
  README.md
  examples/decorator/src/lib.rs
  examples/getitem/src/lib.rs
  examples/maturin-starter/src/submodule.rs
  examples/plugin/plugin_api/src/lib.rs
  examples/setuptools-rust-starter/src/submodule.rs
  examples/word-count/src/lib.rs
  guide/src/class.md
  guide/src/class/numeric.md
  guide/src/class/object.md
  guide/src/ecosystem/async-await.md
  guide/src/ecosystem/logging.md
  guide/src/function.md
  guide/src/function/signature.md
  guide/src/getting_started.md
  guide/src/module.md
  guide/src/python_from_rust.md
  guide/src/trait_bounds.md
  pytests/src/awaitable.rs
  pytests/src/buf_and_str.rs
  pytests/src/comparisons.rs
  pytests/src/datetime.rs
  pytests/src/dict_iter.rs
  pytests/src/enums.rs
  pytests/src/misc.rs
  pytests/src/objstore.rs
  pytests/src/othermod.rs
  pytests/src/path.rs
  pytests/src/pyclasses.rs
  pytests/src/pyfunctions.rs
  pytests/src/sequence.rs
  pytests/src/subclassing.rs
  src/conversions/indexmap.rs
  src/conversions/num_bigint.rs
  src/conversions/num_complex.rs
  src/conversions/rust_decimal.rs
  src/exceptions.rs
  src/lib.rs
  src/types/module.rs
  tests/test_append_to_inittab.rs
  tests/test_module.rs
  tests/test_text_signature.rs
  tests/ui/invalid_pymodule_args.rs
Labels: CI-skip-changelog

#3864 deprecate Py::as_ref
  guide/src/class.md
  guide/src/memory.md
  guide/src/performance.md
  guide/src/trait_bounds.md
  guide/src/types.md
  src/impl_/coroutine.rs
  src/instance.rs
  src/pycell/impl_.rs
  src/pyclass.rs
  tests/ui/invalid_frozen_pyclass_borrow.rs
  tests/ui/invalid_frozen_pyclass_borrow.stderr
Labels: CI-skip-changelog
