Repository PyO3/pyo3, pull requests merged in 2024-09, with the labels that each got.

#4482 Contributing: fix test command
  Contributing.md
Labels: CI-skip-changelog

#4517 ci: fix nightly build
  pyo3-build-config/src/impl_.rs
  pyo3-macros-backend/src/pymethod.rs
  src/version.rs
Labels: CI-skip-changelog

#4527 type_object: fix new clippy complaint about length of doc comment
  guide/src/python-from-rust/calling-existing-code.md
  src/type_object.rs
Labels: CI-skip-changelog

#4525 examples/plugin: fix to use Bound
  examples/plugin/src/main.rs
Labels: CI-skip-changelog

#4533 ci: updates for Rust 1.81
  src/conversions/anyhow.rs
  tests/ui/invalid_cancel_handle.stderr
  tests/ui/invalid_intern_arg.stderr
  tests/ui/invalid_property_args.stderr
  tests/ui/invalid_pyfunctions.stderr
  tests/ui/invalid_pymethod_receiver.stderr
  tests/ui/invalid_pymethods.stderr
  tests/ui/invalid_result_conversion.stderr
Labels: CI-skip-changelog

#4532 Fix typo and missed configs in FFI bindings
  pyo3-ffi/src/cpython/lock.rs
  pyo3-ffi/src/dictobject.rs
  pyo3-ffi/src/listobject.rs
Labels: CI-skip-changelog

#4535 LICENSE: fix up Apache license
  LICENSE-APACHE
Labels: CI-skip-changelog

#4549 fix beta/nightly ci
  src/impl_/pyclass.rs
  src/tests/common.rs
Labels: CI-skip-changelog

#4572 Replace a use of `libc::c_void` with the `std` version
  src/types/capsule.rs
Labels: CI-skip-changelog

#4546 remove continue-on-error from free-threaded CI job
  .github/workflows/ci.yml
  src/impl_/pyclass.rs
  tests/test_gc.rs
Labels: CI-skip-changelog, CI-build-full

#4558 release notes for 0.22.3
  CHANGELOG.md
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/4328.fixed.md
  newsfragments/4349.fixed.md
  newsfragments/4355.added.md
  newsfragments/4355.fixed.md
  newsfragments/4359.fixed.md
  newsfragments/4382.fixed.md
  newsfragments/4396.fixed.md
  newsfragments/4407.fixed.md
  newsfragments/4410.added.md
  newsfragments/4410.fixed.md
  newsfragments/4420.fixed.md
  newsfragments/4420.removed.md
  newsfragments/4445.added.md
  newsfragments/4445.removed.md
  newsfragments/4454.fixed.md
  newsfragments/4456.changed.md
  newsfragments/4461.added.md
  newsfragments/4479.fixed.md
  newsfragments/4481.changed.md
  newsfragments/4511.added.md
Labels: CI-skip-changelog

#4559 migrate `PySequenceMethods` trait bounds
  guide/src/python-from-rust/calling-existing-code.md
  src/types/list.rs
  src/types/sequence.rs
  src/types/tuple.rs
Labels: CI-skip-changelog

#4576 fix flaky tests on free-threaded build
  tests/test_gc.rs
Labels: CI-skip-changelog, CI-build-full

#4583 stop emitting Py_3_6 cfg
  pyo3-build-config/src/impl_.rs
Labels: CI-skip-changelog

#4536 migrate `PySet` to `IntoPyObject`
  src/conversions/hashbrown.rs
  src/conversions/std/set.rs
  src/instance.rs
  src/types/frozenset.rs
  src/types/set.rs
Labels: CI-skip-changelog

#4582 drop support for PyPy 3.7 and 3.8
  .github/workflows/build.yml
  .github/workflows/ci.yml
  README.md
  guide/src/building-and-distribution.md
  newsfragments/4582.packaging.md
  noxfile.py
  pyo3-build-config/src/impl_.rs
  pyo3-ffi/ACKNOWLEDGEMENTS
  pyo3-ffi/README.md
  pyo3-ffi/build.rs
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/datetime.rs
  pyo3-ffi/src/lib.rs
  pyo3-ffi/src/pystate.rs
  src/impl_/pymodule.rs
  src/lib.rs
  src/types/function.rs
Labels: CI-build-full
