Repository PyO3/pyo3, pull requests merged in 2024-04, with the labels that each got.

#4002 refactor `#[setter]` argument extraction
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pymethod.rs
  src/impl_/extract_argument.rs
  tests/ui/static_ref.stderr
Labels: CI-skip-changelog

#4053 fix: allow impl of Ungil for deprecated PyCell in nightly
  src/marker.rs
Labels: CI-skip-changelog

#4066 docs: Fix a typo in Contributing.md
  Contributing.md
Labels: CI-skip-changelog

#4074 Suppress non_local_definitions lint as we often want the non-local effects in macro code
  pyo3-ffi/src/pyport.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/pyfunction.rs
  pyo3-macros-backend/src/pymethod.rs
  src/callback.rs
  src/conversions/std/num.rs
  src/impl_/pyclass.rs
  src/pycell/impl_.rs
  src/types/any.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#4033 Refactoring of `FnArg`
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pyfunction/signature.rs
  pyo3-macros-backend/src/pymethod.rs
  tests/ui/invalid_cancel_handle.rs
  tests/ui/invalid_cancel_handle.stderr
  tests/ui/invalid_pyfunctions.rs
  tests/ui/invalid_pyfunctions.stderr
Labels: CI-skip-changelog

#4087 Specify higher target-lexicon version
  pyo3-build-config/Cargo.toml
Labels: CI-skip-changelog

#4091 release notes for 0.21.2
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/4035.fixed.md
  newsfragments/4045.fixed.md
  newsfragments/4054.fixed.md
  newsfragments/4067.fixed.md
  newsfragments/4073.fixed.md
  newsfragments/4082.changed.md
  pyo3-build-config/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
  pyproject.toml
Labels: CI-skip-changelog

#4096 feature gate deprecated APIs for `PySet`
  src/types/set.rs
Labels: CI-skip-changelog

#4107 feature gate deprecated APIs for `PyTuple`
  src/types/tuple.rs
Labels: CI-skip-changelog

#4101 feature gate deprecated APIs for `PyString`
  src/types/string.rs
Labels: CI-skip-changelog

#4104 fix vectorcall argument handling
  newsfragments/4104.fixed.md
  pyo3-ffi/src/cpython/abstract_.rs
Labels: bugfix

#4108 feature gate deprecated APIs for `PyDict`
  src/conversion.rs
  src/instance.rs
  src/types/dict.rs
  src/types/iterator.rs
  src/types/mapping.rs
Labels: CI-skip-changelog

#4088 Scope macro imports more tightly
  pyo3-macros-backend/src/module.rs
  pytests/src/enums.rs
  tests/test_no_imports.rs
Labels: CI-skip-changelog

#4111 feature gate deprecated APIs for `datetime` types
  src/types/datetime.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#4112 feature gate deprecated APIs for `PyCapsule`
  src/types/capsule.rs
Labels: CI-skip-changelog

#4118 feature gate deprecated APIs for `PyFrozenSet`
  src/types/frozenset.rs
Labels: CI-skip-changelog

#4119 feature gate deprecated APIs for `PyIterator`
  src/types/iterator.rs
Labels: CI-skip-changelog

#4130 Fix lychee for guide
  .netlify/build.sh
  guide/src/parallelism.md
Labels: CI-skip-changelog

#4131 feature gate deprecated APIs for `PyBytes` and `PyPyByteArray`
  src/types/bytearray.rs
  src/types/bytes.rs
Labels: CI-skip-changelog

#4132 feature gate deprecated APIs for `PyEllipsis`, `PyNone` and `PyNotImplemented`
  src/types/ellipsis.rs
  src/types/none.rs
  src/types/notimplemented.rs
Labels: CI-skip-changelog

#4129 Update MSRV to 1.63
  .github/workflows/build.yml
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  build.rs
  guide/src/building-and-distribution.md
  guide/src/getting-started.md
  newsfragments/4129.changed.md
  noxfile.py
  pyo3-build-config/src/lib.rs
  pyo3-ffi/README.md
  pyo3-ffi/build.rs
  pyo3-ffi/src/lib.rs
  src/coroutine/cancel.rs
  src/gil.rs
  src/impl_/pymodule.rs
  src/lib.rs
  tests/test_coroutine.rs
Labels: CI-build-full

#4134 feature gate deprecated APIs for `PyType`, `PyTypeInfo` and `PySuper`
  guide/src/migration.md
  src/conversion.rs
  src/instance.rs
  src/type_object.rs
  src/types/any.rs
  src/types/pysuper.rs
  src/types/typeobject.rs
Labels: CI-skip-changelog

#4136 feature gate deprecated APIs for `PyErr` and exceptions
  src/err/mod.rs
  src/exceptions.rs
  tests/test_exceptions.rs
Labels: CI-skip-changelog

#4139 port `PySequence` tests to `Bound` API
  src/types/sequence.rs
Labels: CI-skip-changelog

#4140 port `PyAny` tests to `Bound` API
  src/types/any.rs
Labels: CI-skip-changelog
