Repository PyO3/pyo3, pull requests merged in 2024-10, with the labels that each got.

#4591 ci: fix benchmarks build
  pyo3-benches/Cargo.toml
  pyo3-benches/benches/bench_any.rs
  pyo3-benches/benches/bench_bigint.rs
  pyo3-benches/benches/bench_call.rs
  pyo3-benches/benches/bench_decimal.rs
  pyo3-benches/benches/bench_dict.rs
  pyo3-benches/benches/bench_extract.rs
  pyo3-benches/benches/bench_frompyobject.rs
  pyo3-benches/benches/bench_intern.rs
  pyo3-benches/benches/bench_list.rs
  pyo3-benches/benches/bench_set.rs
  pyo3-benches/benches/bench_tuple.rs
  pyo3-benches/build.rs
Labels: CI-skip-changelog

#4592 add more `IntoPyObject` impls
  src/conversions/std/osstr.rs
  src/conversions/std/path.rs
  src/pybacked.rs
  src/types/slice.rs
  tests/ui/invalid_property_args.stderr
  tests/ui/missing_intopy.stderr
Labels: CI-skip-changelog

#4594 migrate `PyModule` trait bounds
  src/marker.rs
  src/types/module.rs
Labels: CI-skip-changelog

#4553 Add PyAnyMethods.try_iter and deprecate .iter
  newsfragments/4553.fixed.md
  pyo3-benches/benches/bench_any.rs
  src/conversions/smallvec.rs
  src/types/any.rs
  src/types/iterator.rs
  src/types/mapping.rs
  src/types/sequence.rs
  tests/test_proto_methods.rs
Labels: bugfix, confusing-api, rust

#4587 Add critical section API wrappers
  newsfragments/4587.added.md
  src/sync.rs
Labels: CI-build-full

#4596 add `Bound::from_owned_ptr_unchecked` (crate-private for now)
  src/ffi_ptr_ext.rs
  src/instance.rs
  src/pycell.rs
  src/types/dict.rs
  src/types/weakref/anyref.rs
  src/types/weakref/proxy.rs
  src/types/weakref/reference.rs
Labels: CI-skip-changelog

#4600 ci: move more jobs to macOS arm
  .github/workflows/ci.yml
Labels: CI-skip-changelog, CI-build-full

#4601 Resolve clippy warnings from nightly
  pyo3-ffi/src/cpython/tupleobject.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/pyclass.rs
  src/buffer.rs
  src/conversions/std/cell.rs
  src/conversions/std/num.rs
  src/conversions/std/osstr.rs
  src/conversions/std/path.rs
  src/conversions/std/slice.rs
  src/conversions/std/string.rs
  src/err/mod.rs
  src/impl_/pymethods.rs
  src/instance.rs
  src/pycell.rs
  src/pyclass/gc.rs
  src/types/dict.rs
  src/types/frozenset.rs
  src/types/set.rs
  src/types/tuple.rs
  tests/test_gc.rs
Labels: CI-skip-changelog

#4512 make `GILOnceCell` threadsafe
  guide/src/faq.md
  guide/src/migration.md
  newsfragments/4512.changed.md
  src/conversions/chrono_tz.rs
  src/sync.rs
Labels: CI-build-full

#4610 ci: fix more ubuntu-24.04 failures
  .github/workflows/ci.yml
  src/conversions/chrono_tz.rs
Labels: CI-no-fail-fast, CI-skip-changelog, CI-build-full

#4609 ci: run benchmarks on ubuntu 22.04
  .github/workflows/benches.yml
Labels: CI-skip-changelog

#4607 migrate `IntoPyCallbackOutput` to use `IntoPyObject`
  src/callback.rs
  src/impl_/pymethods.rs
  src/pyclass_init.rs
  src/types/function.rs
  src/types/module.rs
Labels: CI-skip-changelog

#4613 move `callback` module into `impl_`
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pymethod.rs
  src/impl_.rs
  src/impl_/callback.rs
  src/impl_/pyclass.rs
  src/impl_/pymethods.rs
  src/impl_/trampoline.rs
  src/lib.rs
  src/pycell.rs
  src/pyclass_init.rs
  src/types/function.rs
  src/types/module.rs
Labels: CI-skip-changelog

#4563 fix garbage collection in inheritance cases
  newsfragments/4563.fixed.md
  pyo3-macros-backend/src/pymethod.rs
  src/impl_/pymethods.rs
  src/internal/get_slot.rs
  src/pyclass/create_type_object.rs
  tests/test_gc.rs
Labels: CI-build-full

#4615 add release notes from 0.22.4
  CHANGELOG.md
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/4450.changed.md
  newsfragments/4528.added.md
  newsfragments/4563.fixed.md
  newsfragments/4574.fixed.md
  newsfragments/4599.fixed.md
Labels: CI-skip-changelog

#4619 fix `__clear__` slot naming collision with `clear` method
  newsfragments/4619.fixed.md
  pyo3-macros-backend/src/pymethod.rs
  src/tests/hygiene/pymethods.rs
Labels: bugfix

#4629 ci: fix for Rust 1.82
  examples/string-sum/src/lib.rs
Labels: CI-skip-changelog

#4628 test_gc: refactor and silence flaky assertion on freethreaded build
  tests/test_gc.rs
Labels: CI-skip-changelog

#4631 Test free-threaded build on all PRs
  .github/workflows/ci.yml
  noxfile.py
Labels: CI-skip-changelog

#4617 deps: update dependencies
  Cargo.toml
  newsfragments/4617.packaging.md
Labels: CI-build-full

#4577 Add initial free-threading page for the guide
  guide/src/SUMMARY.md
  guide/src/free-threading.md
  guide/src/migration.md
  newsfragments/4577.added.md
  src/lib.rs
Labels: documentation

#4637 ci: fix clippy beta warning
  src/impl_/pyclass.rs
Labels: CI-skip-changelog

#4638 ci: run coverage for the free-threaded build
  .github/workflows/ci.yml
  .github/workflows/coverage-pr-base.yml
  noxfile.py
Labels: CI-skip-changelog

#4642 Attempt to fix the coverage-pr-base workflow
  .github/workflows/coverage-pr-base.yml
Labels: CI-skip-changelog

#4641 Add example Cargo.toml and build.rs for exposing pyo3 cfgs
  pyo3-ffi/src/lib.rs
Labels: CI-skip-changelog

#4439 Make `PyDict` iterator compatible with free-threaded build
  newsfragments/4439.changed.md
  src/lib.rs
  src/types/dict.rs
Labels: CI-build-full

#4645 fix `#[derive(FromPyObject)]` expansion with trait bounds
  newsfragments/4645.fixed.md
  pyo3-macros-backend/src/frompyobject.rs
  tests/test_frompyobject.rs
Labels: bugfix

#4648 Fixup! Typo in description
  README.md
Labels: CI-skip-changelog

#4650 refactor `PyErr` state to reduce blast radius of threading challenge
  src/err/err_state.rs
  src/err/mod.rs
Labels: CI-skip-changelog

#4654 fix compile error for `#[classmethod]`/`#[staticmethod]` on magic methods
  newsfragments/4654.fixed.md
  pyo3-macros-backend/src/method.rs
  src/tests/hygiene/pymethods.rs
Labels: bugfix

#4647 Use `try_for_each` in `into_py_dict`
  src/types/dict.rs
  src/types/list.rs
  src/types/set.rs
Labels: CI-skip-changelog

#4653 migrate `call` API to `IntoPyObject`
  src/conversion.rs
  src/instance.rs
  src/types/any.rs
  src/types/tuple.rs
Labels: CI-skip-changelog

#4658 Update comments now that a std API is stable, but too high MSRV
  src/buffer.rs
Labels: CI-skip-changelog

#4660 switch `PyErrArguments` blanket impl to `IntoPyObject`
  src/err/mod.rs
Labels: CI-skip-changelog

#4655 eagerly normalize fetched exception on Python 3.11 and older
  newsfragments/4655.changed.md
  src/err/err_state.rs
  src/err/mod.rs
Labels: CI-build-full
