Repository PyO3/pyo3, pull requests merged in 2024-06, with the labels that each got.

#4200 fix calling POOL.update_counts() when no `gil-refs` feature
  src/gil.rs
  src/marker.rs
Labels: CI-skip-changelog

#4229 fix incorrect raw identifier handling for the `name` attribute of `pyfunction`s
  pyo3-macros-backend/src/pyfunction.rs
  tests/test_pyfunction.rs
Labels: bugfix, CI-skip-changelog

#4224 fix incorrect `__richcmp__` for `eq_int` only simple enums
  pyo3-macros-backend/src/pyclass.rs
  tests/test_enum.rs
  tests/ui/invalid_pyclass_enum.rs
  tests/ui/invalid_pyclass_enum.stderr
Labels: bugfix, CI-skip-changelog

#4201 remove internal APIs from pyo3-ffi
  newsfragments/4201.changed.md
  src/types/any.rs
  src/types/complex.rs
Labels: CI-skip-changelog

#4240 refactor: use `ptr_from_ref` and ptr `.cast()`
  pyo3-ffi/src/abstract_.rs
  pyo3-ffi/src/cpython/abstract_.rs
  pyo3-ffi/src/datetime.rs
  src/buffer.rs
  src/conversions/num_rational.rs
  src/conversions/std/osstr.rs
  src/exceptions.rs
  src/impl_/extract_argument.rs
  src/impl_/pymodule.rs
  src/instance.rs
  src/internal_tricks.rs
  src/macros.rs
  src/marker.rs
  src/pycell.rs
  src/pyclass/create_type_object.rs
  src/types/any.rs
  src/types/bytearray.rs
  src/types/bytes.rs
  src/types/string.rs
  src/types/tuple.rs
Labels: CI-skip-changelog

#4237 pypy/graalpy: set `Py_LIMITED_API` when `abi3` requested
  newsfragments/4237.changed.md
  pyo3-build-config/src/impl_.rs
  pyo3-ffi/build.rs
  pyo3-ffi/src/cpython/pythonrun.rs
  pyo3-ffi/src/pythonrun.rs
  src/ffi/tests.rs
Labels: CI-build-full

#4244 ci: updates for Rust 1.79
  Cargo.toml
  pyo3-build-config/src/impl_.rs
  src/exceptions.rs
  src/ffi/mod.rs
  src/impl_/pyclass.rs
  src/instance.rs
  src/marker.rs
  src/pycell.rs
  src/sync.rs
  src/types/any.rs
  src/types/bytearray.rs
  src/types/dict.rs
  tests/test_sequence.rs
  tests/ui/invalid_cancel_handle.stderr
  tests/ui/invalid_pyfunctions.stderr
  tests/ui/invalid_pymethod_receiver.stderr
  tests/ui/invalid_pymethods.stderr
  tests/ui/invalid_pymethods_duplicates.stderr
  tests/ui/invalid_result_conversion.stderr
  tests/ui/static_ref.stderr
Labels: CI-skip-changelog

#4220 Improve the span and message for return types of pymethod/functions
  pyo3-macros-backend/src/deprecations.rs
  pyo3-macros-backend/src/frompyobject.rs
  pyo3-macros-backend/src/konst.rs
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pyfunction.rs
  pyo3-macros-backend/src/pyimpl.rs
  pyo3-macros-backend/src/pymethod.rs
  pyo3-macros-backend/src/quotes.rs
  pyo3-macros-backend/src/utils.rs
  src/conversion.rs
  src/impl_/wrap.rs
  tests/ui/invalid_result_conversion.stderr
  tests/ui/missing_intopy.stderr
Labels: CI-skip-changelog

#4270 improve code generated by `c_str!` macro
  pyo3-ffi/src/lib.rs
Labels: CI-skip-changelog

#4268 Bump diagnostic_namespace rust version
  pyo3-build-config/src/lib.rs
Labels: CI-skip-changelog

#4239 ci: minor cleanups following 1.63 MSRV
  .github/workflows/build.yml
  .github/workflows/ci.yml
  Cargo.toml
  guide/src/features.md
  noxfile.py
  pyo3-ffi/src/methodobject.rs
  src/conversions/chrono.rs
  src/conversions/std/array.rs
  src/marker.rs
  tests/ui/invalid_pymethods_duplicates.rs
  tests/ui/invalid_pymethods_duplicates.stderr
Labels: CI-skip-changelog

#4272 Update dependencies to reflect minimal versions
  Cargo.toml
  pyo3-ffi-check/macro/Cargo.toml
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
Labels: CI-skip-changelog

#4275 make datetime from timestamp tests compare against Python result
  pytests/tests/test_datetime.py
Labels: CI-skip-changelog

#4276 document FnType and refactor FnType::self_arg
  pyo3-macros-backend/src/method.rs
Labels: CI-skip-changelog
