Repository PyO3/pyo3, pull requests merged in 2024-07, with the labels that each got.

#4302 Add pyo3-arrow to README
  README.md
Labels: CI-skip-changelog

#4313 simplify implementation of `Py::clone_ref`
  src/instance.rs
Labels: CI-skip-changelog

#4320 remove the gil-ref deprecations infrastructure
  pyo3-macros-backend/src/frompyobject.rs
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pymethod.rs
  src/impl_/deprecations.rs
  src/macros.rs
  tests/test_compile_error.rs
  tests/ui/deprecations.rs
  tests/ui/deprecations.stderr
Labels: CI-skip-changelog

#4273 ci: check minimal-versions on MSRV feature powerset
  .github/workflows/build.yml
  .github/workflows/ci.yml
  Cargo.toml
  noxfile.py
Labels: CI-skip-changelog, CI-build-full

#4338 remove most deprecated gil-ref APIs in `src/types`
  guide/src/types.md
  src/conversion.rs
  src/conversions/std/slice.rs
  src/conversions/std/string.rs
  src/err/mod.rs
  src/instance.rs
  src/internal_tricks.rs
  src/types/boolobject.rs
  src/types/bytearray.rs
  src/types/bytes.rs
  src/types/capsule.rs
  src/types/complex.rs
  src/types/datetime.rs
  src/types/dict.rs
  src/types/ellipsis.rs
  src/types/float.rs
  src/types/frozenset.rs
  src/types/function.rs
  src/types/iterator.rs
  src/types/list.rs
  src/types/mapping.rs
  src/types/memoryview.rs
  src/types/mod.rs
  src/types/module.rs
  src/types/none.rs
  src/types/notimplemented.rs
  src/types/pysuper.rs
  src/types/sequence.rs
  src/types/set.rs
  src/types/slice.rs
  src/types/string.rs
  src/types/traceback.rs
  src/types/tuple.rs
  src/types/typeobject.rs
  src/types/weakref/anyref.rs
  src/types/weakref/proxy.rs
  src/types/weakref/reference.rs
  tests/test_no_imports.rs
Labels: CI-skip-changelog

#4324 use FFI calls for refcounting on all abi3 versions
  newsfragments/4324.changed.md
  pyo3-ffi/src/object.rs
Labels: CI-build-full

#4341 clean up `test_no_imports` tests
  tests/test_class_new.rs
  tests/test_no_imports.rs
Labels: CI-skip-changelog

#4342 remove more gil-ref APIs
  guide/src/memory.md
  src/buffer.rs
  src/conversion.rs
  src/err/mod.rs
  src/exceptions.rs
  src/instance.rs
  src/lib.rs
  src/marshal.rs
  src/types/any.rs
  src/types/bytearray.rs
  src/types/complex.rs
  src/types/datetime.rs
  src/types/ellipsis.rs
  src/types/frozenset.rs
  src/types/iterator.rs
  src/types/mapping.rs
  src/types/memoryview.rs
  src/types/mod.rs
  src/types/none.rs
  src/types/notimplemented.rs
  src/types/sequence.rs
  src/types/set.rs
  src/types/tuple.rs
  src/types/weakref/anyref.rs
  src/types/weakref/proxy.rs
  src/types/weakref/reference.rs
Labels: CI-skip-changelog

#4359 fix: adding tests for pyclass hygiene cases
  newsfragments/4359.fixed.md
  pyo3-macros-backend/src/pyclass.rs
  src/tests/hygiene/pyclass.rs
Labels: CI-skip-changelog

#4375 fix clippy-beta
  src/types/mod.rs
Labels: CI-skip-changelog

#4376 release notes for 0.22.2
  CHANGELOG.md
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/4324.changed.md
  newsfragments/4327.packaging.md
  newsfragments/4330.changed.md
  newsfragments/4346.changed.md
  newsfragments/4353.fixed.md
Labels: CI-skip-changelog

#4343 remove gil-refs from `wrap_pyfunction` and `from_py_with`
  guide/src/function.md
  guide/src/function/error-handling.md
  guide/src/function/signature.md
  guide/src/migration.md
  pytests/src/enums.rs
  src/conversions/anyhow.rs
  src/conversions/eyre.rs
  src/coroutine/waker.rs
  src/derive_utils.rs
  src/err/mod.rs
  src/exceptions.rs
  src/impl_/extract_argument.rs
  src/impl_/frompyobject.rs
  src/impl_/pyfunction.rs
  src/lib.rs
  src/macros.rs
  src/marker.rs
  src/prelude.rs
  src/pycell.rs
  src/sync.rs
  src/tests/hygiene/pymodule.rs
  src/types/bytearray.rs
  src/types/iterator.rs
  src/types/weakref/proxy.rs
  src/types/weakref/reference.rs
  tests/test_anyhow.rs
  tests/test_bytes.rs
  tests/test_coroutine.rs
  tests/test_enum.rs
  tests/test_exceptions.rs
  tests/test_macros.rs
  tests/test_methods.rs
  tests/test_pyfunction.rs
  tests/test_string.rs
  tests/test_text_signature.rs
  tests/test_various.rs
  tests/test_wrap_pyfunction_deduction.rs
  tests/ui/invalid_result_conversion.rs
Labels: CI-skip-changelog

#4385 fix nightly ci
  guide/src/class.md
  guide/src/class/object.md
  guide/src/faq.md
  src/conversion.rs
  src/types/mod.rs
  tests/test_declarative_module.rs
  tests/test_macros.rs
Labels: CI-skip-changelog, CI-build-full

#4380 add back `PyTuple::new`
  guide/src/conversions/traits.md
  guide/src/migration.md
  guide/src/python-from-rust/function-calls.md
  guide/src/types.md
  pytests/src/datetime.rs
  src/conversion.rs
  src/impl_/extract_argument.rs
  src/impl_/pymodule.rs
  src/instance.rs
  src/types/datetime.rs
  src/types/list.rs
  src/types/sequence.rs
  src/types/tuple.rs
  src/types/typeobject.rs
  tests/test_frompyobject.rs
  tests/test_various.rs
Labels: CI-skip-changelog

#4386 reintroduce `PyList` constructors
  guide/src/conversions/traits.md
  guide/src/exception.md
  guide/src/performance.md
  guide/src/trait-bounds.md
  guide/src/types.md
  pyo3-benches/benches/bench_frompyobject.rs
  pyo3-benches/benches/bench_list.rs
  pyo3-benches/benches/bench_tuple.rs
  src/conversions/smallvec.rs
  src/lib.rs
  src/macros.rs
  src/marker.rs
  src/sync.rs
  src/tests/hygiene/pymethods.rs
  src/types/any.rs
  src/types/dict.rs
  src/types/iterator.rs
  src/types/list.rs
  src/types/module.rs
  src/types/sequence.rs
  src/types/tuple.rs
  tests/test_frompyobject.rs
  tests/test_getter_setter.rs
  tests/test_methods.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#4397 fix ui tests
  tests/test_compile_error.rs
Labels: CI-skip-changelog

#4387 Add back `PyBytes::new`
  guide/src/conversions/traits.md
  pytests/src/buf_and_str.rs
  src/conversions/anyhow.rs
  src/conversions/eyre.rs
  src/conversions/num_bigint.rs
  src/conversions/std/slice.rs
  src/pybacked.rs
  src/tests/hygiene/pymethods.rs
  src/types/bytes.rs
  tests/test_bytes.rs
Labels: CI-skip-changelog
