Repository PyO3/pyo3, pull requests merged in 2024-11, with the labels that each got.

#4674 fix unintentional `unsafe_op_in_unsafe_fn` trigger
  newsfragments/4674.fixed.md
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pymethod.rs
  tests/ui/forbid_unsafe.rs
Labels: bugfix

#4680 add blanket `IntoPyObject` implementation for `&&T`
  src/conversion.rs
  src/tests/hygiene/misc.rs
  tests/ui/invalid_property_args.stderr
  tests/ui/missing_intopy.stderr
Labels: CI-skip-changelog

#4686 Run free-threaded CI on MacOS
  .github/workflows/ci.yml
Labels: CI, CI-skip-changelog

#4694 rework complex enum field conversion
  newsfragments/4694.fixed.md
  pyo3-macros-backend/src/pyclass.rs
  src/impl_/pyclass.rs
  tests/test_enum.rs
Labels: bugfix

#4707 fix `clippy::wildcard_import` firing on `#[pyclass]`
  pyo3-macros-backend/src/pyclass.rs
Labels: bugfix, CI-skip-changelog

#4706 simplify a few uses of `BoundObject`
  src/coroutine.rs
  tests/test_methods.rs
  tests/test_module.rs
Labels: CI-skip-changelog

#4715 release: 0.23.1
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  pyo3-build-config/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-ffi/README.md
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
  pyproject.toml
  tests/ui/reject_generics.stderr
Labels: CI-skip-changelog

#4725 Fix ambiguous associated item error
  newsfragments/4725.fixed.md
  pyo3-macros-backend/src/intopyobject.rs
  pyo3-macros-backend/src/pyclass.rs
  tests/test_compile_error.rs
  tests/ui/ambiguous_associated_items.rs
Labels: bugfix, rust

#4719 Free-threaded build config fixes
  guide/src/free-threading.md
  newsfragments/4719.fixed.md
  pyo3-build-config/src/impl_.rs
  pyo3-ffi/build.rs
Labels: free-threading

#4731 add release notes for 0.23.2
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/4708.added.md
  newsfragments/4719.fixed.md
  newsfragments/4725.fixed.md
  pyo3-build-config/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-ffi/README.md
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
  pyproject.toml
  tests/ui/reject_generics.stderr
Labels: CI-skip-changelog

#4737 fix clippy beta
  examples/Cargo.toml
  pyo3-build-config/Cargo.toml
  pyo3-build-config/src/impl_.rs
  pyo3-ffi/Cargo.toml
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
  pytests/Cargo.toml
Labels: CI-skip-changelog

#4741 ci: updates for Rust 1.83
  tests/ui/invalid_pyfunctions.stderr
  tests/ui/static_ref.stderr
Labels: CI-skip-changelog

#4750 ci: test debug builds using 3.13.0
  .github/workflows/ci.yml
Labels: CI-skip-changelog, CI-build-full
