Repository PyO3/pyo3, pull requests merged in 2024-05, with the labels that each got.

#4141 feature gate deprecated APIs for `PySlice`
  src/types/slice.rs
Labels: CI-skip-changelog

#4142 feature gate deprecated APIs for `Py`
  guide/src/memory.md
  guide/src/python-from-rust/function-calls.md
  guide/src/types.md
  src/err/mod.rs
  src/instance.rs
  src/marker.rs
  src/types/any.rs
  src/types/dict.rs
Labels: CI-skip-changelog

#4144 feature gate deprecated APIs for `PyBuffer`
  src/buffer.rs
Labels: CI-skip-changelog

#4145 feature gate deprecated APIs for `PyFloat` and `PyComplex`
  src/conversions/num_complex.rs
  src/types/complex.rs
  src/types/float.rs
Labels: CI-skip-changelog

#4147 fix `clippy-beta` ci workflow
  pyo3-build-config/src/lib.rs
Labels: CI-skip-changelog

#4150 ci: updates for Rust 1.78
  pytests/src/othermod.rs
  src/pyclass/create_type_object.rs
  tests/test_compile_error.rs
  tests/ui/abi3_nativetype_inheritance.stderr
  tests/ui/invalid_argument_attributes.rs
  tests/ui/invalid_argument_attributes.stderr
  tests/ui/invalid_cancel_handle.stderr
  tests/ui/invalid_intern_arg.rs
  tests/ui/invalid_intern_arg.stderr
  tests/ui/invalid_property_args.rs
  tests/ui/invalid_property_args.stderr
  tests/ui/invalid_proto_pymethods.rs
  tests/ui/invalid_proto_pymethods.stderr
  tests/ui/invalid_pyfunction_signatures.rs
  tests/ui/invalid_pyfunction_signatures.stderr
  tests/ui/invalid_pyfunctions.rs
  tests/ui/invalid_pyfunctions.stderr
  tests/ui/invalid_pymethod_receiver.rs
  tests/ui/invalid_pymethod_receiver.stderr
  tests/ui/invalid_pymethods.rs
  tests/ui/invalid_pymethods.stderr
  tests/ui/invalid_pymethods_duplicates.stderr
  tests/ui/missing_intopy.stderr
  tests/ui/pyclass_send.rs
  tests/ui/traverse.rs
  tests/ui/traverse.stderr
Labels: CI-skip-changelog

#4146 fix `check-guide` ci workflow
  noxfile.py
Labels: CI-skip-changelog

#4152 feature gate deprecated APIs for `PyMemoryView`
  src/types/memoryview.rs
Labels: CI-skip-changelog

#4151 feature gate deprecated APIs for `PyModule`
  guide/src/python-from-rust/calling-existing-code.md
  src/marker.rs
  src/types/module.rs
Labels: CI-skip-changelog

#4149 feature gate deprecated APIs for `marshal`
  src/marshal.rs
Labels: CI-skip-changelog

#4154 feature gate deprecated APIs for `PyCFunction`
  src/types/function.rs
Labels: CI-skip-changelog

#4117 handle `#[pyo3(from_py_with = ...)]` on dunder (`__magic__`) methods
  newsfragments/4117.fixed.md
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pymethod.rs
  tests/test_class_basics.rs
  tests/ui/deprecations.rs
  tests/ui/deprecations.stderr
Labels: bugfix

#4159 feature gate deprecated APIs for `PyBool`
  src/types/boolobject.rs
Labels: CI-skip-changelog

#4163 emit `cargo:rustc-check-cfg=CHECK_CFG` for `pyo3`s config names
  build.rs
  guide/src/migration.md
  pyo3-build-config/src/impl_.rs
  pyo3-build-config/src/lib.rs
  pyo3-ffi/build.rs
  src/marker.rs
  src/tests/hygiene/pyclass.rs
Labels: CI-skip-changelog

#4157 store the `FnArg` ident as a `Cow` instead of a reference
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pyclass.rs
Labels: CI-skip-changelog

#4160 feature gate APIs using `into_gil_ref` (Part 1)
  src/conversions/std/array.rs
  src/instance.rs
  src/internal_tricks.rs
  src/macros.rs
  src/tests/common.rs
  src/tests/hygiene/pymodule.rs
  src/types/bytearray.rs
  src/types/complex.rs
  src/types/dict.rs
  src/types/frozenset.rs
  src/types/iterator.rs
  src/types/list.rs
  src/types/mapping.rs
  src/types/memoryview.rs
  src/types/mod.rs
  src/types/module.rs
  src/types/sequence.rs
  src/types/set.rs
  src/types/tuple.rs
  tests/test_no_imports.rs
  tests/ui/deprecations.rs
  tests/ui/deprecations.stderr
Labels: CI-skip-changelog

#4166 feature gate APIs using `into_gil_ref` (Part 2)
  guide/src/conversions/traits.md
  guide/src/exception.md
  guide/src/memory.md
  guide/src/migration.md
  guide/src/types.md
  pytests/src/pyclasses.rs
  pytests/src/sequence.rs
  pytests/tests/test_pyclasses.py
  src/conversion.rs
  src/conversions/chrono.rs
  src/conversions/std/osstr.rs
  src/conversions/std/path.rs
  src/derive_utils.rs
  src/err/mod.rs
  src/exceptions.rs
  src/impl_/deprecations.rs
  src/impl_/extract_argument.rs
  src/instance.rs
  src/pycell.rs
  src/tests/hygiene/pyfunction.rs
  src/types/any.rs
  src/types/bytearray.rs
  src/types/float.rs
  src/types/iterator.rs
  src/types/memoryview.rs
  src/types/mod.rs
  src/types/num.rs
  tests/test_class_basics.rs
  tests/test_compile_error.rs
  tests/test_methods.rs
  tests/test_module.rs
  tests/test_proto_methods.rs
  tests/ui/deprecations.stderr
  tests/ui/invalid_result_conversion.stderr
Labels: CI-skip-changelog

#4167 remove function pointer wrappers no longer needed for MSRV
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pyimpl.rs
  pyo3-macros-backend/src/pymethod.rs
  src/impl_/pyclass/lazy_type_object.rs
  src/impl_/pymethods.rs
  src/pyclass/create_type_object.rs
  src/types/function.rs
Labels: CI-skip-changelog

#4169 feature gate deprecated more APIs for `Py`
  guide/src/python-from-rust/calling-existing-code.md
  src/err/mod.rs
  src/macros.rs
  src/marker.rs
Labels: CI-skip-changelog

#4172 feature gate `as/into_gil_ref` APIs (Part 3)
  guide/src/migration.md
  guide/src/types.md
  src/conversion.rs
  src/conversions/std/slice.rs
  src/conversions/std/string.rs
  src/impl_/frompyobject.rs
  src/impl_/pyfunction.rs
  src/impl_/pymethods.rs
  src/instance.rs
  src/pycell.rs
  src/tests/hygiene/misc.rs
  src/tests/hygiene/pymodule.rs
  src/types/string.rs
  tests/test_wrap_pyfunction_deduction.rs
Labels: CI-skip-changelog

#4173 feature gate deprecated APIs for `Python`
  guide/src/memory.md
  src/conversion.rs
  src/gil.rs
  src/lib.rs
  src/marker.rs
  src/prelude.rs
  src/pycell.rs
Labels: CI-skip-changelog

#4175 split more impl blocks (preparation of `PyCell` feature gate)
  src/types/boolobject.rs
  src/types/bytearray.rs
  src/types/bytes.rs
  src/types/capsule.rs
  src/types/complex.rs
  src/types/datetime.rs
  src/types/float.rs
  src/types/slice.rs
  src/types/traceback.rs
  src/types/typeobject.rs
Labels: CI-skip-changelog

#4176 Updates comments regarding the reference pool that were inaccurate
  src/gil.rs
Labels: CI-skip-changelog

#4177 feature gate `PyCell`
  Cargo.toml
  guide/src/class.md
  guide/src/migration.md
  pyo3-build-config/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-macros-backend/Cargo.toml
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros/Cargo.toml
  pyproject.toml
  src/conversion.rs
  src/err/mod.rs
  src/exceptions.rs
  src/impl_/deprecations.rs
  src/impl_/pyclass.rs
  src/instance.rs
  src/lib.rs
  src/macros.rs
  src/prelude.rs
  src/pycell.rs
  src/pycell/impl_.rs
  src/pyclass.rs
  src/type_object.rs
  src/types/any.rs
  src/types/mod.rs
  tests/test_compile_error.rs
  tests/ui/deprecations.stderr
  tests/ui/invalid_intern_arg.stderr
  tests/ui/invalid_pymethods_duplicates.stderr
  tests/ui/wrong_aspyref_lifetimes.stderr
Labels: CI-skip-changelog

#4168 emit rustc-check-cfg only on rust 1.80+
  pyo3-build-config/src/lib.rs
Labels: CI-skip-changelog

#4187 Change `GILGuard` to be able to represent a GIL that was already held
  src/gil.rs
Labels: CI-skip-changelog

#4188 Move GIL counting from GILPool to GILGuard
  src/gil.rs
  src/impl_/trampoline.rs
  src/marker.rs
Labels: CI-skip-changelog

#4185 Emit a better error for abi3 inheritance
  pyo3-build-config/src/lib.rs
  src/impl_/pyclass.rs
  tests/test_compile_error.rs
  tests/ui/abi3_inheritance.rs
  tests/ui/abi3_inheritance.stderr
  tests/ui/abi3_nativetype_inheritance.stderr
Labels: CI-skip-changelog

#4181 feature gate deprecated APIs for `GILPool`
  src/gil.rs
  src/impl_/not_send.rs
  src/lib.rs
  src/marker.rs
Labels: CI-skip-changelog

#4193 Remove OWNED_OBJECTS thread local when GILPool is disabled.
  src/gil.rs
Labels: CI-skip-changelog

#4199 ci: adjust test to avoid type inference
  src/pybacked.rs
Labels: CI-skip-changelog

#4184 ci: start testing on 3.13-dev
  .github/workflows/ci.yml
  newsfragments/4184.packaging.md
  noxfile.py
  pyo3-ffi/build.rs
  pyo3-ffi/src/cpython/code.rs
  pyo3-ffi/src/cpython/compile.rs
  pyo3-ffi/src/cpython/import.rs
  pyo3-ffi/src/cpython/initconfig.rs
  pyo3-ffi/src/cpython/longobject.rs
  pyo3-ffi/src/cpython/mod.rs
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/longobject.rs
  pytests/noxfile.py
  pytests/pyproject.toml
  pytests/tests/test_misc.py
  src/conversions/num_bigint.rs
  src/conversions/std/num.rs
Labels: CI-build-full

#4209 ci: turn off gh-pages benchmarks
  .github/workflows/gh-pages.yml
  README.md
Labels: CI-skip-changelog

#4222 docs: fix typo
  guide/src/types.md
Labels: CI-skip-changelog
