Repository PyO3/pyo3, pull requests merged in 2024-12, with the labels that each got.

#4753 fix another `unsafe_op_in_unsafe_fn` trigger
  pyo3-macros-backend/src/params.rs
  tests/ui/forbid_unsafe.rs
Labels: bugfix, CI-skip-changelog

#4774 Avoid interpolating values into bash
  .github/workflows/coverage-pr-base.yml
Labels: CI-skip-changelog

#4770 fix lints in `pyo3-benches`
  pyo3-benches/benches/bench_call.rs
  pyo3-benches/benches/bench_extract.rs
  pyo3-benches/benches/bench_intopyobject.rs
  pyo3-benches/benches/bench_pyobject.rs
  pyo3-benches/benches/bench_set.rs
  pyo3-benches/benches/bench_tuple.rs
Labels: CI-skip-changelog

#4779 ci: fix coverage-pr-base `BASE_REF` expansion
  .github/workflows/coverage-pr-base.yml
Labels: CI-skip-changelog

#4785 Fix chrono deprecation warning
  src/conversions/chrono.rs
Labels: CI-skip-changelog

#4794 fix `#[pyclass]` could not be named `Probe`
  newsfragments/4794.fixed.md
  pyo3-macros-backend/src/pyclass.rs
  tests/test_compile_error.rs
  tests/ui/pyclass_probe.rs
  tests/ui/pyclass_send.stderr
Labels: bugfix

#4818 docs: Fix copy/paste typo in PyListMethods docs
  src/types/list.rs
Labels: documentation

#4817 switch trait sealing in `impl_` module
  src/impl_/pyclass.rs
  src/internal_tricks.rs
Labels: CI-skip-changelog

#4802 Fix struct layouts on GraalPy
  newsfragments/4802.fixed.md
  pyo3-ffi/src/abstract_.rs
  pyo3-ffi/src/cpython/abstract_.rs
  pyo3-ffi/src/cpython/complexobject.rs
  pyo3-ffi/src/cpython/floatobject.rs
  pyo3-ffi/src/cpython/genobject.rs
  pyo3-ffi/src/cpython/listobject.rs
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/cpython/objimpl.rs
  pyo3-ffi/src/cpython/pyerrors.rs
  pyo3-ffi/src/cpython/tupleobject.rs
  pyo3-ffi/src/cpython/unicodeobject.rs
  pyo3-ffi/src/datetime.rs
  pyo3-ffi/src/object.rs
  pyo3-ffi/src/pyhash.rs
  src/types/mod.rs
Labels: CI-build-full

#4832 fix error with complex enums with many fields
  newsfragments/4832.fixed.md
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  src/tests/hygiene/pyclass.rs
Labels: bugfix
