Repository PyO3/pyo3, pull requests merged in 2024-08, with the labels that each got.

#4393 Fix typo: Add missing closing bracket
  pyo3-macros-backend/src/pyclass.rs
  tests/ui/deprecations.stderr
Labels: CI-skip-changelog

#4402 reintroduce `PyBool` constructors
  guide/src/exception.md
  src/impl_/pyclass.rs
  src/types/any.rs
  src/types/boolobject.rs
  tests/test_class_attributes.rs
Labels: CI-skip-changelog

#4403 reintroduce `PyCapsule` constructors
  src/instance.rs
  src/types/capsule.rs
  src/types/function.rs
Labels: CI-skip-changelog

#4409 Reintroduce constructors for `PyByteArray`, `PyComplex`, `PyFloat`, `PyEllipsis`, `PyFrozenSet`
  guide/src/class/numeric.md
  src/conversions/hashbrown.rs
  src/conversions/num_complex.rs
  src/conversions/std/set.rs
  src/marker.rs
  src/pybacked.rs
  src/tests/hygiene/pymethods.rs
  src/types/any.rs
  src/types/bytearray.rs
  src/types/complex.rs
  src/types/ellipsis.rs
  src/types/float.rs
  src/types/frozenset.rs
Labels: CI-skip-changelog

#4396 Add missing #[allow(unsafe_code)] attributes
  newsfragments/4396.fixed.md
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  src/impl_/pyclass.rs
  src/macros.rs
  src/tests/hygiene/mod.rs
  src/types/mod.rs
Labels: bugfix, proc-macro, rust

#4398 add back new `marshal` APIs
  src/marshal.rs
Labels: CI-skip-changelog

#4399 remove some unneeded `AsPyPointer` implementations
  src/conversion.rs
  src/types/any.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#4429 ci: pin `zope.interface<7`
  .github/workflows/ci.yml
  noxfile.py
  pytests/noxfile.py
Labels: CI-skip-changelog, CI-build-full

#4426 Update test_misc.py for 3.13 subinterpreter changes
  pytests/tests/test_misc.py
Labels: CI-skip-changelog

#4430 ci: install cargo-codspeed binary
  .github/workflows/benches.yml
Labels: CI-skip-changelog

#4431 reintroduce `PyString` constructors
  guide/src/conversions/traits.md
  guide/src/types.md
  src/conversion.rs
  src/conversions/std/ipaddr.rs
  src/conversions/std/string.rs
  src/err/mod.rs
  src/ffi/tests.rs
  src/instance.rs
  src/marker.rs
  src/pybacked.rs
  src/sync.rs
  src/types/any.rs
  src/types/string.rs
  src/types/typeobject.rs
  tests/test_pyself.rs
  tests/ui/not_send2.rs
Labels: CI-skip-changelog

#4432 reintroduce a bunch of type contructors
  pytests/src/buf_and_str.rs
  src/coroutine.rs
  src/err/mod.rs
  src/impl_/wrap.rs
  src/marker.rs
  src/types/any.rs
  src/types/frozenset.rs
  src/types/function.rs
  src/types/iterator.rs
  src/types/memoryview.rs
  src/types/none.rs
  src/types/notimplemented.rs
  src/types/pysuper.rs
  src/types/set.rs
  src/types/slice.rs
  src/types/typeobject.rs
  tests/test_class_basics.rs
  tests/test_exceptions.rs
  tests/test_pyfunction.rs
  tests/test_super.rs
  tests/ui/invalid_closure.rs
  tests/ui/invalid_closure.stderr
Labels: CI-skip-changelog

#4433 ci: install `cargo-careful` from binary again
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#4436 Reintroduces `Python::import` and `Python::get_type`
  README.md
  guide/src/class.md
  guide/src/exception.md
  guide/src/migration.md
  guide/src/python-from-rust/calling-existing-code.md
  pyo3-macros-backend/src/pyclass.rs
  src/buffer.rs
  src/conversions/chrono.rs
  src/conversions/chrono_tz.rs
  src/conversions/num_bigint.rs
  src/conversions/std/time.rs
  src/coroutine/waker.rs
  src/err/mod.rs
  src/exceptions.rs
  src/gil.rs
  src/impl_/extract_argument.rs
  src/impl_/pymodule.rs
  src/instance.rs
  src/lib.rs
  src/macros.rs
  src/marker.rs
  src/pyclass_init.rs
  src/sync.rs
  src/tests/common.rs
  src/types/any.rs
  src/types/dict.rs
  src/types/string.rs
  src/types/traceback.rs
  src/types/typeobject.rs
  tests/test_class_attributes.rs
  tests/test_class_basics.rs
  tests/test_class_new.rs
  tests/test_coroutine.rs
  tests/test_datetime.rs
  tests/test_datetime_import.rs
  tests/test_enum.rs
  tests/test_gc.rs
  tests/test_getter_setter.rs
  tests/test_inheritance.rs
  tests/test_macro_docs.rs
  tests/test_macros.rs
  tests/test_mapping.rs
  tests/test_methods.rs
  tests/test_multiple_pymethods.rs
  tests/test_proto_methods.rs
  tests/test_sequence.rs
  tests/test_static_slots.rs
  tests/test_super.rs
  tests/test_text_signature.rs
  tests/test_variable_arguments.rs
  tests/ui/invalid_intern_arg.rs
  tests/ui/invalid_intern_arg.stderr
Labels: CI-skip-changelog

#4437 ci: fix nightly warning about unreachable pattern
  src/sync.rs
Labels: CI-skip-changelog

#4404 reintroduce `PyModule` constructors
  examples/maturin-starter/src/lib.rs
  examples/plugin/src/main.rs
  examples/setuptools-rust-starter/src/lib.rs
  guide/src/class.md
  guide/src/class/numeric.md
  guide/src/conversions/traits.md
  guide/src/function/signature.md
  guide/src/module.md
  guide/src/python-from-rust/calling-existing-code.md
  guide/src/python-from-rust/function-calls.md
  newsfragments/4404.changed.md
  pyo3-benches/benches/bench_call.rs
  pyo3-ffi/src/moduleobject.rs
  pytests/src/lib.rs
  src/conversions/anyhow.rs
  src/conversions/eyre.rs
  src/conversions/num_bigint.rs
  src/conversions/num_complex.rs
  src/instance.rs
  src/marker.rs
  src/pyclass_init.rs
  src/types/any.rs
  src/types/capsule.rs
  src/types/module.rs
  src/types/typeobject.rs
  tests/test_class_basics.rs
  tests/test_class_new.rs
  tests/test_inheritance.rs
  tests/test_module.rs
  tests/test_proto_methods.rs
  tests/test_various.rs
Labels: CI-build-full

#4438 restore derive(Debug) for ffi types where it was removed
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/datetime.rs
Labels: CI-skip-changelog

#4421 Initial free threaded bindings
  .github/workflows/ci.yml
  newsfragments/4421.added.md
  newsfragments/4421.fixed.md
  pyo3-build-config/src/impl_.rs
  pyo3-build-config/src/lib.rs
  pyo3-ffi/build.rs
  pyo3-ffi/src/cpython/initconfig.rs
  pyo3-ffi/src/cpython/lock.rs
  pyo3-ffi/src/cpython/mod.rs
  pyo3-ffi/src/cpython/weakrefobject.rs
  pyo3-ffi/src/moduleobject.rs
  pyo3-ffi/src/object.rs
  src/impl_/pymodule.rs
  tests/test_dict_iter.rs
Labels: CI-build-full

#4444 [docs] Update rust-from-python.md [no-ci]
  guide/src/rust-from-python.md
Labels: CI-skip-changelog

#4446 Add more `IntoPyObject` impls
  src/conversion.rs
  src/conversions/chrono.rs
  src/conversions/chrono_tz.rs
  src/conversions/either.rs
  src/conversions/hashbrown.rs
  src/conversions/indexmap.rs
  src/conversions/num_bigint.rs
  src/conversions/num_complex.rs
  src/conversions/num_rational.rs
  src/conversions/rust_decimal.rs
  src/conversions/smallvec.rs
  src/conversions/std/array.rs
  src/conversions/std/cell.rs
  src/conversions/std/ipaddr.rs
  src/conversions/std/map.rs
  src/conversions/std/num.rs
  src/conversions/std/option.rs
  src/conversions/std/osstr.rs
  src/conversions/std/path.rs
  src/conversions/std/set.rs
  src/conversions/std/string.rs
  src/conversions/std/time.rs
  src/err/mod.rs
  src/types/boolobject.rs
  src/types/float.rs
  tests/ui/missing_intopy.stderr
Labels: CI-skip-changelog

#4457 Reintroduces `datetime` constructors
  pytests/src/datetime.rs
  src/conversions/chrono.rs
  src/conversions/std/time.rs
  src/ffi/tests.rs
  src/types/datetime.rs
  src/types/mod.rs
  tests/test_datetime.rs
  tests/test_datetime_import.rs
Labels: CI-skip-changelog

#4460 fix weakref proxy tests on free-threaded build
  src/types/weakref/proxy.rs
Labels: CI-skip-changelog

#4459 Delete iter_dict_nosegv test
  tests/test_dict_iter.rs
Labels: CI-skip-changelog

#4462 ci: swap .python-version file for explicit versions in actions yml
  .github/workflows/benches.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .python-version
Labels: CI-skip-changelog, CI-build-full

#4449 `IntoPyObject` for `#[pyo3(get)]`
  guide/src/migration.md
  pyo3-macros-backend/src/pymethod.rs
  src/impl_/pyclass.rs
  tests/ui/invalid_property_args.stderr
Labels: CI-skip-changelog

#4461 ffi: add compat functions for no-argument calls
  newsfragments/4461.added.md
  pyo3-ffi/src/compat/mod.rs
  pyo3-ffi/src/compat/py_3_9.rs
  src/types/any.rs
Labels: CI-build-full

#4468 impl `IntoPyObject` for tuples
  src/types/tuple.rs
Labels: CI-skip-changelog

#4473 only show free-threaded warning on free-threaded build
  pyo3-ffi/build.rs
Labels: CI-skip-changelog

#4469 Fix tests for cargo stress on free-threaded build
  Cargo.toml
  src/gil.rs
  tests/test_datetime_import.rs
Labels: CI-skip-changelog

#4478 fix wrong trait bound `IntoPyObject` impls for `Hash` collections
  src/conversions/hashbrown.rs
  src/conversions/std/map.rs
  src/conversions/std/set.rs
  src/types/mapping.rs
Labels: CI-skip-changelog

#4475 reintroduce `PyErr` constructors and methods
  guide/src/python-from-rust/calling-existing-code.md
  src/conversions/anyhow.rs
  src/conversions/chrono.rs
  src/conversions/eyre.rs
  src/coroutine.rs
  src/err/impls.rs
  src/err/mod.rs
  src/exceptions.rs
  src/impl_/extract_argument.rs
  src/impl_/pyclass.rs
  src/impl_/trampoline.rs
  src/instance.rs
  src/tests/common.rs
  src/types/dict.rs
  src/types/mapping.rs
  src/types/sequence.rs
  src/types/string.rs
  src/types/traceback.rs
  src/types/weakref/proxy.rs
  tests/test_coroutine.rs
  tests/test_exceptions.rs
Labels: CI-skip-changelog

#4483 ci: run coverage jobs in `pull_request_target` context
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: CI-skip-changelog

#4484 reintroduce `PyTypeInfo` methods
  guide/src/class/numeric.md
  src/err/mod.rs
  src/impl_/pymodule.rs
  src/marker.rs
  src/tests/common.rs
  src/type_object.rs
  src/types/any.rs
  src/types/code.rs
  src/types/ellipsis.rs
  src/types/mapping.rs
  src/types/none.rs
  src/types/notimplemented.rs
  src/types/pysuper.rs
  src/types/sequence.rs
  src/types/typeobject.rs
Labels: CI-skip-changelog

#4476 skip tests using thread-unsafe constructs on free-threaded build
  src/conversions/chrono.rs
  src/err/mod.rs
  src/tests/common.rs
  src/tests/mod.rs
  tests/test_buffer_protocol.rs
  tests/test_class_basics.rs
  tests/test_exceptions.rs
Labels: CI-skip-changelog

#4480 initial migration of the trait bounds to `IntoPyObject` (`PyAnyMethods`)
  guide/src/migration.md
  src/conversions/chrono.rs
  src/conversions/std/num.rs
  src/instance.rs
  src/prelude.rs
  src/types/any.rs
  src/types/bytes.rs
  src/types/datetime.rs
  src/types/mapping.rs
Labels: CI-skip-changelog

#4486 reintroduce `PyBuffer::get`
  pytests/src/buf_and_str.rs
  src/buffer.rs
  tests/test_buffer.rs
  tests/test_buffer_protocol.rs
Labels: CI-skip-changelog

#4488 ci: run codecov job using PR head
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#4487 Remove the `BoundObject` impl for `&Bound`, use `Borrowed` instead
  src/conversion.rs
  src/instance.rs
  src/pycell.rs
Labels: CI-skip-changelog

#4491 reintroduce weakref constructors
  src/types/weakref/anyref.rs
  src/types/weakref/proxy.rs
  src/types/weakref/reference.rs
Labels: CI-skip-changelog

#4489 restrict `IntoPyObject::Error` to convert into `PyErr`
  src/conversion.rs
  src/conversions/chrono.rs
  src/conversions/either.rs
  src/conversions/hashbrown.rs
  src/conversions/indexmap.rs
  src/conversions/smallvec.rs
  src/conversions/std/array.rs
  src/conversions/std/map.rs
  src/conversions/std/set.rs
  src/conversions/std/slice.rs
  src/conversions/std/vec.rs
  src/impl_/pyclass.rs
  src/impl_/wrap.rs
  src/instance.rs
  src/types/any.rs
  src/types/mapping.rs
  src/types/tuple.rs
Labels: CI-skip-changelog

#4492 reintroduce `PySet` constructors
  src/conversions/hashbrown.rs
  src/conversions/std/set.rs
  src/types/set.rs
Labels: CI-skip-changelog

#4494 fixup `Py_NotImplemented` in 3.13 abi3
  pyo3-ffi/src/object.rs
Labels: CI-skip-changelog

#4501 use unique module names in unit and integration tests
  Cargo.toml
  src/conversions/num_bigint.rs
  src/conversions/num_complex.rs
  src/instance.rs
  src/tests/common.rs
  src/types/any.rs
  src/types/typeobject.rs
  tests/test_module.rs
Labels: CI-skip-changelog

#4506 reintroduce `PyUnicodeDecodeError` constructors
  src/exceptions.rs
  src/types/string.rs
Labels: CI-skip-changelog

#4505 reintroduce `Py::call` and `Py::call_method`
  examples/decorator/src/lib.rs
  guide/src/python-from-rust/function-calls.md
  src/instance.rs
  src/types/any.rs
Labels: CI-skip-changelog

#4453 Error at compile-time when a non-subclassable class is being subclassed
  newsfragments/4453.changed.md
  pyo3-macros-backend/src/pyclass.rs
  src/exceptions.rs
  src/impl_/pyclass.rs
  src/pyclass_init.rs
  src/types/any.rs
  src/types/complex.rs
  src/types/datetime.rs
  src/types/dict.rs
  src/types/float.rs
  src/types/frozenset.rs
  src/types/mod.rs
  src/types/set.rs
  src/types/weakref/reference.rs
  tests/test_compile_error.rs
  tests/test_declarative_module.rs
  tests/test_inheritance.rs
  tests/test_macros.rs
  tests/ui/abi3_inheritance.stderr
  tests/ui/abi3_nativetype_inheritance.stderr
  tests/ui/invalid_base_class.rs
  tests/ui/invalid_base_class.stderr
Labels: CI-build-full
