Repository PyO3/pyo3, pull requests merged in 2024-01, with the labels that each got.

#3721 Use a definite version specification when depending on pyo3-build-config.
  Cargo.toml
  pyo3-ffi/Cargo.toml
Labels: CI-skip-changelog

#3702 introduce PyIterator::from_bound_object
  src/coroutine.rs
  src/types/any.rs
  src/types/frozenset.rs
  src/types/iterator.rs
  src/types/set.rs
Labels: CI-skip-changelog

#3722 Fix missing feature flags in implementation of Either conversion.
  .github/workflows/ci.yml
  Cargo.toml
  src/conversions/either.rs
Labels: CI-skip-changelog, CI-build-full

#3723 Fix doc build
  .github/workflows/ci.yml
  Cargo.toml
  src/conversions/either.rs
Labels: CI-skip-changelog

#3724 re-add emit_pyo3_cfgs for pyo3 0.20.0 compatibility
  pyo3-build-config/src/impl_.rs
Labels: CI-skip-changelog

#3711 add `call_bound` and `call_method_bound`
  examples/decorator/src/lib.rs
  guide/src/python_from_rust.md
  src/instance.rs
  src/types/any.rs
  tests/ui/invalid_result_conversion.stderr
Labels: CI-skip-changelog

#3727 release notes for 0.20.2
  CHANGELOG.md
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
Labels: CI-skip-changelog

#3738 fix some nightly lints 2024-01-12
  guide/src/class.md
  guide/src/class/object.md
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/utils.rs
  src/tests/hygiene/misc.rs
  tests/test_frompyobject.rs
Labels: CI-skip-changelog

#3742 improve performance of successful int extract by ~30% by avoiding calls to `__index__` where redundant
  newsfragments/3742.changed.md
  src/conversions/std/num.rs
Labels: CI-build-full

#3582 Full ADT support with pyclass for complex enums
  guide/src/class.md
  newsfragments/3582.added.md
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  pytests/noxfile.py
  pytests/src/enums.rs
  pytests/src/lib.rs
  pytests/tests/test_enums.py
  pytests/tests/test_enums_match.py
  tests/test_compile_error.rs
  tests/ui/invalid_pyclass_enum.rs
  tests/ui/invalid_pyclass_enum.stderr
  tests/ui/invalid_pymethod_enum.rs
  tests/ui/invalid_pymethod_enum.stderr
Labels: CI-no-fail-fast, CI-build-full

#3763 implement `PyTracebackMethods` and `PySliceMethods`
  guide/src/python_from_rust.md
  src/err/err_state.rs
  src/err/mod.rs
  src/exceptions.rs
  src/prelude.rs
  src/types/mod.rs
  src/types/slice.rs
  src/types/traceback.rs
  tests/ui/invalid_result_conversion.stderr
Labels: CI-skip-changelog

#3765 remove internal uses of `_Py_NewRef`
  src/impl_/pyclass.rs
  src/types/any.rs
  tests/test_buffer.rs
  tests/test_buffer_protocol.rs
Labels: CI-skip-changelog

#3743 add bound constructors for `PySet` and `PyFrozenSet`
  pyo3-benches/benches/bench_set.rs
  src/conversions/hashbrown.rs
  src/conversions/std/set.rs
  src/types/frozenset.rs
  src/types/set.rs
Labels: CI-skip-changelog

#3755 add list bound constructors
  guide/src/conversions/traits.md
  guide/src/exception.md
  guide/src/migration.md
  guide/src/types.md
  pyo3-benches/benches/bench_frompyobject.rs
  pyo3-benches/benches/bench_list.rs
  pyo3-benches/benches/bench_tuple.rs
  src/conversions/smallvec.rs
  src/instance.rs
  src/macros.rs
  src/marker.rs
  src/sync.rs
  src/tests/hygiene/pymethods.rs
  src/types/dict.rs
  src/types/list.rs
  src/types/module.rs
  src/types/sequence.rs
  tests/test_frompyobject.rs
  tests/test_getter_setter.rs
  tests/test_methods.rs
  tests/test_proto_methods.rs
Labels: CI-skip-changelog

#3767 implement `PyComplexMethods`
  guide/src/class/numeric.md
  src/conversions/num_complex.rs
  src/tests/hygiene/pymethods.rs
  src/types/complex.rs
Labels: CI-skip-changelog

#3769 remove `test_pep_587`
  Cargo.toml
  tests/test_pep_587.rs
Labels: CI-skip-changelog

#3774 add `PyString::new_bound`
  guide/src/conversions/traits.md
  pyo3-benches/benches/bench_extract.rs
  pyo3-benches/benches/bench_frompyobject.rs
  src/conversion.rs
  src/conversions/std/ipaddr.rs
  src/conversions/std/string.rs
  src/err/mod.rs
  src/ffi/tests.rs
  src/instance.rs
  src/marker.rs
  src/types/any.rs
  src/types/string.rs
  tests/test_pyself.rs
  tests/ui/not_send2.rs
  tests/ui/not_send2.stderr
Labels: CI-skip-changelog

#3770 implement `PyCapsuleMethods`
  src/prelude.rs
  src/types/capsule.rs
  src/types/function.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#3783 remove bench of `GILPool::new`
  pyo3-benches/benches/bench_gil.rs
Labels: CI-skip-changelog

#3781 change return type of `intern!` macro to `&Bound<PyString>`
  guide/src/migration.md
  src/impl_/coroutine.rs
  src/instance.rs
  src/sync.rs
  src/types/mod.rs
  src/types/module.rs
  src/types/string.rs
Labels: CI-skip-changelog

#3786 add `Bound` constructors for `PyByteArray` and `PyMemoryView`
  src/types/bytearray.rs
  src/types/memoryview.rs
Labels: CI-skip-changelog
