Repository PyO3/pyo3, pull requests merged in 2025-05, with the labels that each got.

#5070 unify `IntoPyObject`/`FromPyObject` derive attributes
  newsfragments/5070.fixed.md
  pyo3-macros-backend/src/derive_attributes.rs
  pyo3-macros-backend/src/frompyobject.rs
  pyo3-macros-backend/src/intopyobject.rs
  pyo3-macros-backend/src/lib.rs
  tests/test_frompy_intopy_roundtrip.rs
  tests/ui/invalid_frompy_derive.stderr
  tests/ui/invalid_intopy_derive.stderr
Labels: bugfix, proc-macro

#5116 bump supported GraalPy version to 24.2
  .github/workflows/build.yml
  .github/workflows/ci.yml
  README.md
  newsfragments/5116.packaging.md
  src/ffi/tests.rs
  src/tests/hygiene/misc.rs
  src/types/mappingproxy.rs
  src/types/string.rs
  tests/test_append_to_inittab.rs
  tests/test_inheritance.rs
  tests/test_super.rs
Labels: CI-build-full

#5122 docs: Fix md formatting on checkboxes
  Contributing.md
Labels: CI-skip-changelog

#5091 ci: move main build to use `test-rust` nox job
  .github/workflows/build.yml
  newsfragments/5091.fixed.md
  noxfile.py
  pyo3-ffi/src/cpython/mod.rs
  pyo3-ffi/src/cpython/pyhash.rs
  src/conversions/jiff.rs
Labels: CI-no-fail-fast, CI-build-full

#5130 revert tz change for jiff test
  src/conversions/jiff.rs
Labels: CI-skip-changelog

#5134 Fix clippy errors
  build.rs
  src/buffer.rs
  src/conversions/std/array.rs
  src/conversions/std/ipaddr.rs
  src/conversions/std/num.rs
  src/err/impls.rs
  src/err/mod.rs
  src/exceptions.rs
  src/impl_/frompyobject.rs
  src/impl_/pyclass.rs
  src/impl_/pyclass/lazy_type_object.rs
  src/instance.rs
  src/pyclass/create_type_object.rs
  src/types/num.rs
  src/types/string.rs
  src/types/weakref/proxy.rs
  tests/test_arithmetics.rs
  tests/test_class_formatting.rs
  tests/test_datetime.rs
  tests/test_frompyobject.rs
  tests/test_methods.rs
  tests/test_pyerr_debug_unformattable.rs
  tests/test_pyfunction.rs
Labels: CI-skip-changelog

#5135 more format args inlining
  examples/decorator/src/lib.rs
  pyo3-build-config/src/errors.rs
  pyo3-build-config/src/impl_.rs
  pyo3-build-config/src/lib.rs
  pyo3-ffi/build.rs
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  pytests/src/pyclasses.rs
  src/conversions/anyhow.rs
  src/conversions/bigdecimal.rs
  src/conversions/chrono.rs
  src/conversions/chrono_tz.rs
  src/conversions/eyre.rs
  src/conversions/jiff.rs
  src/conversions/rust_decimal.rs
  src/conversions/time.rs
  src/inspect/types.rs
  src/types/typeobject.rs
  tests/test_compile_error.rs
Labels: CI-skip-changelog

#5133 Don't expose PyASCIIObjectState on Python3.14 and newer
  newsfragments/5133.removed.md
  pyo3-ffi/src/cpython/unicodeobject.rs
  src/ffi/tests.rs
Labels: CI-build-full

#5044 Implement `OnceExt` & `MutexExt` for `parking_lot` & `lock_api`
  Cargo.toml
  guide/src/class/thread-safety.md
  guide/src/features.md
  newsfragments/5044.added.md
  src/sealed.rs
  src/sync.rs
Labels: CI-build-full

#5128 release: 0.25.0
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/3977.added.md
  newsfragments/4811.fixed.md
  newsfragments/4926.added.md
  newsfragments/4970.changed.md
  newsfragments/4982.removed.md
  newsfragments/5010.removed.md
  newsfragments/5011.added.md
  newsfragments/5037.fixed.md
  newsfragments/5044.added.md
  newsfragments/5054.added.md
  newsfragments/5055.added.md
  newsfragments/5055.changed.md
  newsfragments/5057.added.md
  newsfragments/5064.added.md
  newsfragments/5064.changed.md
  newsfragments/5064.removed.md
  newsfragments/5070.fixed.md
  newsfragments/5071.added.md
  newsfragments/5071.changed.md
  newsfragments/5071.removed.md
  newsfragments/5079.changed.md
  newsfragments/5085.added.md
  newsfragments/5086.added.md
  newsfragments/5091.fixed.md
  newsfragments/5096.added.md
  newsfragments/5097.removed.md
  newsfragments/5101.added.md
  newsfragments/5105.removed.md
  newsfragments/5109.changed.md
  newsfragments/5110.changed.md
  newsfragments/5112.added.md
  newsfragments/5114.added.md
  newsfragments/5115.changed.md
  newsfragments/5116.packaging.md
  newsfragments/5117.added.md
  newsfragments/5120.fixed.md
  newsfragments/5123.fixed.md
  newsfragments/5133.removed.md
  pyo3-build-config/Cargo.toml
  pyo3-ffi/Cargo.toml
  pyo3-ffi/README.md
  pyo3-introspection/Cargo.toml
  pyo3-macros-backend/Cargo.toml
  pyo3-macros/Cargo.toml
  pyproject.toml
  tests/ui/reject_generics.stderr
Labels: CI-build-full

#5087 Implements basic method introspection
  pyo3-introspection/src/introspection.rs
  pyo3-introspection/src/model.rs
  pyo3-introspection/src/stubs.rs
  pyo3-introspection/tests/test.rs
  pyo3-macros-backend/src/introspection.rs
  pyo3-macros-backend/src/pyfunction.rs
  pyo3-macros-backend/src/pyimpl.rs
  pyo3-macros-backend/src/pymethod.rs
  pytests/src/pyclasses.rs
  pytests/stubs/pyclasses.pyi
  pytests/tests/test_pyclasses.py
Labels: CI-skip-changelog

#5147 ci: updates for Rust 1.87
  tests/ui/invalid_proto_pymethods.stderr
  tests/ui/pyclass_send.stderr
Labels: CI-skip-changelog

#5145 Add Windows ARM64 Build configuration
  .github/workflows/build.yml
  .github/workflows/ci.yml
  newsfragments/5145.packaging.md
Labels: CI-build-full

#5154 Frame ffi
  newsfragments/5154.added.md
  newsfragments/5154.removed.md
  pyo3-ffi/src/cpython/frameobject.rs
  pyo3-ffi/src/cpython/mod.rs
  pyo3-ffi/src/cpython/pyframe.rs
  pyo3-ffi/src/lib.rs
  pyo3-ffi/src/pyframe.rs
  pyo3-ffi/src/pystate.rs
  pyo3-ffi/src/pytypedefs.rs
Labels: CI-build-full

#5121 Updates to better support ormsgpack on GraalPy.
  newsfragments/5121.added.md
  newsfragments/5121.changed.md
  pyo3-ffi/src/abstract_.rs
  pyo3-ffi/src/compat/py_3_9.rs
  pyo3-ffi/src/cpython/abstract_.rs
  pyo3-ffi/src/cpython/bytesobject.rs
  pyo3-ffi/src/object.rs
  src/types/bytes.rs
Labels: CI-build-full
