Repository PyO3/pyo3, pull requests merged in 2025-03, with the labels that each got.

#4954 bump `inventory` minimum version
  Cargo.toml
  newsfragments/4954.packaging.md
Labels: dependencies

#4874 hang instead of pthread_exit during interpreter shutdown
  newsfragments/4874.changed.md
  pyo3-build-config/src/lib.rs
  pyo3-ffi/src/pystate.rs
  pytests/src/misc.rs
  pytests/tests/test_hammer_gil_in_thread.py
Labels: CI-build-full

#4963 fix 3.7 builds
  noxfile.py
Labels: CI-skip-changelog, CI-build-full

#4972 fix `check-msrv` ci job by resolving to latest compatible dependencies
  examples/decorator/Cargo.toml
  examples/getitem/Cargo.toml
  examples/maturin-starter/Cargo.toml
  examples/plugin/Cargo.toml
  examples/setuptools-rust-starter/Cargo.toml
  examples/word-count/Cargo.toml
  noxfile.py
  pyo3-ffi/examples/sequential/Cargo.toml
  pyo3-ffi/examples/string-sum/Cargo.toml
Labels: CI-skip-changelog, CI-build-full

#4993 ci: make emscripten job only save cache on main
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#4994 Migrate lints to use 2024 edition practice of `unsafe_op_in_unsafe_fn`
  Cargo.toml
  pyo3-build-config/src/lib.rs
  pyo3-ffi/src/lib.rs
  src/err/err_state.rs
  src/ffi_ptr_ext.rs
  src/gil.rs
  src/impl_/extract_argument.rs
  src/impl_/pyclass.rs
  src/impl_/pyclass_init.rs
  src/impl_/pymethods.rs
  src/impl_/trampoline.rs
  src/instance.rs
  src/internal/get_slot.rs
  src/lib.rs
  src/marker.rs
  src/py_result_ext.rs
  src/pycell/impl_.rs
  src/pyclass/create_type_object.rs
  src/pyclass_init.rs
  src/types/any.rs
  src/types/bytearray.rs
  src/types/bytes.rs
  src/types/capsule.rs
  src/types/datetime.rs
  src/types/function.rs
  src/types/list.rs
  src/types/mappingproxy.rs
  src/types/string.rs
  src/types/tuple.rs
  src/types/typeobject.rs
  src/types/weakref/anyref.rs
  tests/test_buffer.rs
  tests/test_buffer_protocol.rs
  tests/test_gc.rs
  tests/test_pyfunction.rs
Labels: CI-no-fail-fast, CI-skip-changelog, CI-build-full

#5007 replace quansight-labs/setup-python with actions/setup-python
  .github/workflows/ci.yml
Labels: CI-skip-changelog, CI-build-full

#5015 fix `#[pyfunction]` option parsing
  newsfragments/5015.fixed.md
  pyo3-macros-backend/src/pyfunction.rs
  src/tests/hygiene/pyfunction.rs
Labels: bugfix, proc-macro

#5018 Simplify PyFunctionArgument impl on &Bound<T>
  src/impl_/extract_argument.rs
Labels: CI-skip-changelog

#5002 split `PyFunctionArgument` to specialize `Option`
  guide/src/class.md
  newsfragments/5002.fixed.md
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  pyo3-macros-backend/src/utils.rs
  src/impl_/extract_argument.rs
  src/impl_/pyclass/probes.rs
  tests/test_pyfunction.rs
  tests/ui/invalid_cancel_handle.stderr
Labels: bugfix, proc-macro

#5019 ci: mark many rust code blocks as no_run
  guide/src/async-await.md
  guide/src/class.md
  guide/src/class/numeric.md
  guide/src/class/object.md
  guide/src/class/protocols.md
  guide/src/class/thread-safety.md
  guide/src/conversions/traits.md
  guide/src/ecosystem/logging.md
  guide/src/ecosystem/tracing.md
  guide/src/exception.md
  guide/src/faq.md
  guide/src/features.md
  guide/src/free-threading.md
  guide/src/function.md
  guide/src/function/signature.md
  guide/src/getting-started.md
  guide/src/migration.md
  guide/src/module.md
  guide/src/performance.md
  guide/src/trait-bounds.md
  pyo3-build-config/src/impl_.rs
  pyo3-ffi/README.md
  pyo3-ffi/src/lib.rs
  src/conversion.rs
  src/conversions/num_bigint.rs
  src/conversions/num_rational.rs
  src/conversions/rust_decimal.rs
  src/conversions/uuid.rs
  src/impl_/pymethods.rs
  src/lib.rs
  src/marker.rs
  src/pycell.rs
  src/pyclass.rs
  src/types/module.rs
  src/types/pysuper.rs
Labels: CI-skip-changelog

#5020 ci: save caches on main only by default
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: CI-skip-changelog
