Repository PyO3/pyo3, pull requests merged in 2025-01, with the labels that each got.

#4773 ci: add more tests for cross-compilation
  .github/workflows/ci.yml
Labels: CI-skip-changelog, CI-build-full

#4788 Fix PyDict issues on free-threaded build
  newsfragments/4788.fixed.md
  src/types/dict.rs
Labels: free-threading

#4838 Allow useless conversion
  pyo3-macros-backend/src/quotes.rs
Labels: CI-skip-changelog

#4789 Implement locked iteration for PyList
  newsfragments/4789.added.md
  newsfragments/4789.changed.md
  src/types/list.rs
Labels: free-threading

#4846 ci: updates for Rust 1.84
  .github/workflows/ci.yml
  emscripten/Makefile
  noxfile.py
  pyo3-build-config/src/impl_.rs
  pyo3-ffi/src/datetime.rs
  src/types/any.rs
  src/types/module.rs
  tests/ui/invalid_cancel_handle.stderr
  tests/ui/invalid_property_args.stderr
  tests/ui/invalid_pycallargs.stderr
  tests/ui/invalid_pyclass_args.stderr
  tests/ui/invalid_pyfunctions.stderr
  tests/ui/invalid_pymethod_receiver.stderr
  tests/ui/invalid_pymethods.stderr
  tests/ui/invalid_result_conversion.stderr
  tests/ui/not_send.stderr
  tests/ui/not_send2.stderr
  tests/ui/pyclass_send.stderr
Labels: CI-skip-changelog, CI-build-full

#4853 pyo3-ffi: expose `PyObject_Vectorcall(Method)` on the stable abi on 3.12+
  newsfragments/4853.added.md
  pyo3-ffi/src/abstract_.rs
  pyo3-ffi/src/cpython/abstract_.rs
  src/instance.rs
  src/types/tuple.rs
Labels: performance, CI-no-fail-fast, CI-build-full

#4865 Run tests on GitHub hosted arm64 Linux runner
  .github/workflows/ci.yml
  pyo3-ffi-check/Cargo.toml
  pyo3-ffi-check/build.rs
Labels: CI-skip-changelog
