Repository PyO3/pyo3, pull requests merged in 2025-04, with the labels that each got.

#5030 fix `unused_imports` warning for `IsOption` probe (#5002)
  newsfragments/5030.fixed.md
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pymethod.rs
  tests/ui/pyclass_probe.rs
Labels: bugfix, proc-macro

#5041 update UI tests for Rust 1.86
  tests/ui/invalid_intern_arg.stderr
  tests/ui/static_ref.stderr
Labels: CI-skip-changelog

#5032 Makes Clippy beta happy
  pyo3-ffi/src/lib.rs
  pyo3-macros-backend/src/method.rs
  src/err/mod.rs
  src/impl_/pyclass.rs
  src/impl_/pyclass_init.rs
  src/instance.rs
  src/internal_tricks.rs
  src/pycell/impl_.rs
  src/type_object.rs
  src/types/any.rs
  src/types/boolobject.rs
  src/types/sequence.rs
  src/types/weakref/anyref.rs
  src/types/weakref/proxy.rs
  src/types/weakref/reference.rs
  tests/test_exceptions.rs
Labels: CI-skip-changelog

#5045 ci: avoid even more caches being saved when not main
  .github/workflows/benches.yml
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#5047 Drop stray executable bit from non-executable text files
  guide/src/conversions/traits.md
  pyo3-macros-backend/src/attributes.rs
  pyo3-macros-backend/src/intopyobject.rs
  src/conversions/std/ipaddr.rs
  src/conversions/std/time.rs
  tests/test_intopyobject.rs
  tests/ui/invalid_intopy_derive.rs
  tests/ui/invalid_intopy_with.rs
  tests/ui/invalid_intopy_with.stderr
Labels: CI-skip-changelog

#5034 Introspection: Fixes Mach-O parsing
  pyo3-introspection/src/introspection.rs
Labels: CI-skip-changelog

#5048 ci: change default Python version to 3.13
  .github/workflows/benches.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/coverage-pr-base.yml
  .github/workflows/gh-pages.yml
  newsfragments/5048.fixed.md
  pyo3-ffi/src/cpython/code.rs
Labels: CI-skip-changelog, CI-build-full

#5042 clean up setuptools starter example to use `pyproject.toml` configuration
  examples/setuptools-rust-starter/noxfile.py
  examples/setuptools-rust-starter/pyproject.toml
  examples/setuptools-rust-starter/setup.cfg
  examples/setuptools-rust-starter/setup.py
  examples/word-count/noxfile.py
Labels: CI-skip-changelog

#5027 ci: release cargo crate from git tag
  .github/workflows/release.yaml
Labels: CI-skip-changelog

#5060 docs: Update building-and-distribution.md
  guide/src/building-and-distribution.md
Labels: CI-skip-changelog

#5063 ci: silence `ffi-check` for private `_PyCoLineInstrumentationData` on 3.13
  pyo3-ffi-check/macro/src/lib.rs
Labels: CI-skip-changelog

#5052 ci: reduce number of jobs & improve coverage measurement
  .github/workflows/build.yml
  .github/workflows/ci.yml
  examples/setuptools-rust-starter/noxfile.py
  noxfile.py
Labels: CI-skip-changelog, CI-build-full

#5025 Introspection: add function signatures
  pyo3-introspection/src/introspection.rs
  pyo3-introspection/src/model.rs
  pyo3-introspection/src/stubs.rs
  pyo3-macros-backend/src/introspection.rs
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/module.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pyfunction.rs
  pyo3-macros-backend/src/pyfunction/signature.rs
  pytests/src/pyfunctions.rs
  pytests/stubs/pyfunctions.pyi
  pytests/tests/test_pyfunctions.py
Labels: CI-skip-changelog

#5083 release notes for 0.24.1 and 0.24.2
  CHANGELOG.md
  README.md
  Releasing.md
  examples/decorator/.template/pre-script.rhai
  examples/maturin-starter/.template/pre-script.rhai
  examples/plugin/.template/pre-script.rhai
  examples/setuptools-rust-starter/.template/pre-script.rhai
  examples/word-count/.template/pre-script.rhai
  newsfragments/4969.added.md
  newsfragments/4978.added.md
  newsfragments/4981.fixed.md
  newsfragments/4984.added.md
  newsfragments/4988.fixed.md
  newsfragments/4992.added.md
  newsfragments/5002.fixed.md
  newsfragments/5008.fixed.md
  newsfragments/5013.added.md
  newsfragments/5015.fixed.md
  newsfragments/5030.fixed.md
  newsfragments/5048.fixed.md
  newsfragments/5050.fixed.md
  pyo3-ffi/README.md
Labels: CI-skip-changelog

#5090 ci: fix clippy jobs only running Python 3.7 checks
  noxfile.py
Labels: CI-no-fail-fast

#5095 Fixes pytests tests when using Python 3.7
  pytests/tests/test_pyfunctions.py
Labels: CI-skip-changelog, CI-build-full

#5098 docs: fix typo in `Ipv4Addr` and `Ipv6Addr` type names
  guide/src/conversions/tables.md
Labels: CI-skip-changelog

#4811 Bump supported cpython version to 3.14 for testing
  .github/workflows/build.yml
  .github/workflows/ci.yml
  Cargo.toml
  newsfragments/4811.fixed.md
  noxfile.py
  pyo3-build-config/Cargo.toml
  pyo3-ffi-check/build.rs
  pyo3-ffi/Cargo.toml
  pyo3-ffi/build.rs
  pyo3-ffi/src/abstract_.rs
  pyo3-ffi/src/cpython/dictobject.rs
  pyo3-ffi/src/cpython/funcobject.rs
  pyo3-ffi/src/cpython/genobject.rs
  pyo3-ffi/src/cpython/initconfig.rs
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/cpython/pyerrors.rs
  pyo3-ffi/src/cpython/tupleobject.rs
  pyo3-ffi/src/cpython/unicodeobject.rs
  pyo3-ffi/src/lib.rs
  pyo3-ffi/src/object.rs
  pyo3-ffi/src/pystate.rs
  pyo3-ffi/src/refcount.rs
  pytests/pytest.ini
  src/ffi/tests.rs
  src/types/dict.rs
Labels: FFI, CI-build-full, free-threading

#5102 remove TODO in `pyo3-build-config`
  pyo3-build-config/src/lib.rs
Labels: CI-skip-changelog

#5096 add declarative module level constants export
  guide/src/module.md
  newsfragments/5096.added.md
  pyo3-macros-backend/src/module.rs
  src/tests/hygiene/pymodule.rs
  tests/test_declarative_module.rs
  tests/ui/invalid_pymodule_trait.stderr
Labels: proc-macro
