Repository PyO3/pyo3, pull requests merged in 2025-02, with the labels that each got.

#4886 Fix manual_ok_err clippy lint on nightly
  src/types/set.rs
Labels: refactoring, CI-skip-changelog, rust

#4867 Update tested GraalPy version in CI
  .github/workflows/build.yml
  .github/workflows/ci.yml
  pytests/tests/test_comparisons.py
Labels: CI-skip-changelog, CI-build-full

#4901 docs: fix typo in class.md
  guide/src/class.md
Labels: CI-skip-changelog

#4760 Add PyPy3.11
  .github/workflows/ci.yml
  newsfragments/4760.packaging.md
  noxfile.py
  pyo3-ffi/build.rs
  pyo3-ffi/src/abstract_.rs
  pyo3-ffi/src/cpython/abstract_.rs
  pyo3-ffi/src/cpython/genobject.rs
  pyo3-ffi/src/cpython/mod.rs
  pyo3-ffi/src/cpython/object.rs
  pyo3-ffi/src/cpython/objimpl.rs
  pyo3-ffi/src/cpython/pyframe.rs
  pyo3-ffi/src/cpython/pystate.rs
  pyo3-ffi/src/cpython/unicodeobject.rs
  pyo3-ffi/src/object.rs
  pyo3-ffi/src/pybuffer.rs
  pyo3-ffi/src/pyerrors.rs
  src/ffi/tests.rs
Labels: CI-build-full

#4903 Update jiff to v0.2
  .github/workflows/ci.yml
  Cargo.toml
  guide/src/features.md
  noxfile.py
  src/conversions/jiff.rs
  src/types/datetime.rs
  src/types/mod.rs
Labels: CI-skip-changelog

#4918 restore skipped asserts on free-threaded build
  tests/test_gc.rs
Labels: CI-skip-changelog

#4921 Use a critical section to serialize adding builtins to globals
  newsfragments/4921.fixed.md
  src/marker.rs
Labels: free-threading

#4917 Add support for type hinting objects
  newsfragments/4917.added.md
  pyo3-ffi/src/genericaliasobject.rs
  pyo3-ffi/src/lib.rs
  src/types/genericalias.rs
  src/types/mod.rs
Labels: CI-build-full

#4840 Improve diagnostic for invalid function passed to from_py_with
  pyo3-macros-backend/src/frompyobject.rs
  pyo3-macros-backend/src/params.rs
  pyo3-macros-backend/src/pymethod.rs
  tests/ui/invalid_argument_attributes.rs
  tests/ui/invalid_argument_attributes.stderr
Labels: CI-skip-changelog

#4940 fix broken link in docs
  guide/src/conversions/traits.md
Labels: CI-skip-changelog

#4946 Reduce runtime of slow test
  src/types/mappingproxy.rs
Labels: CI-skip-changelog

#4948 Avoid data races in BorrowFlag
  newsfragments/4948.fixed.md
  src/pycell/impl_.rs
Labels: free-threading

#4941 add `#[pyo3(rename_all = "...")]` for `#[derive(FromPyObject)]`
  guide/src/conversions/traits.md
  newsfragments/4941.added.md
  pyo3-macros-backend/src/frompyobject.rs
  tests/test_frompyobject.rs
  tests/ui/invalid_frompy_derive.rs
  tests/ui/invalid_frompy_derive.stderr
Labels: enhancement, proc-macro

#4934 add a MutexExt trait to avoid deadlocks using Mutex::lock()
  guide/src/class/thread-safety.md
  guide/src/free-threading.md
  newsfragments/4934.added.md
  src/sealed.rs
  src/sync.rs
Labels: free-threading

#4938 Don't use gc.get_objects on the free-threaded build
  tests/test_gc.rs
Labels: CI-skip-changelog, free-threading
