Repository PyO3/pyo3, pull requests merged in 2025-08, with the labels that each got.

#5233 introduce `PyClassGuard(Mut)` as future replacement for `PyRef(Mut)`
  newsfragments/5233.added.md
  pyo3-macros-backend/src/method.rs
  pyo3-macros-backend/src/pyclass.rs
  pyo3-macros-backend/src/pymethod.rs
  src/conversion.rs
  src/impl_/extract_argument.rs
  src/impl_/pyclass.rs
  src/impl_/pymethods.rs
  src/instance.rs
  src/lib.rs
  src/pyclass.rs
  src/pyclass/guard.rs
  tests/ui/invalid_cancel_handle.stderr
  tests/ui/invalid_frozen_pyclass_borrow.stderr
  tests/ui/invalid_pymethod_enum.stderr
  tests/ui/invalid_pymethods.stderr
Labels: CI-no-fail-fast

#5315 Drop const_concat! macro and str-focused const combine functions
  pyo3-macros-backend/src/introspection.rs
  pyo3-macros-backend/src/pyclass.rs
  src/impl_/concat.rs
  src/impl_/pyclass/doc.rs
Labels: CI-skip-changelog

#5327 Fix comment on PyBuffer::buf_ptr
  src/buffer.rs
Labels: CI-skip-changelog

#5335 unpin nightly
  .github/workflows/ci.yml
Labels: CI-skip-changelog

#5317 panic on attach if interpreter is shutting down
  newsfragments/5317.added.md
  newsfragments/5317.changed.md
  newsfragments/5317.fixed.md
  newsfragments/5317.removed.md
  pyo3-ffi/src/cpython/pylifecycle.rs
  pyo3-ffi/src/pylifecycle.rs
  src/internal/state.rs
  src/marker.rs
Labels: CI-build-full

#5361 fixup `Py::cast_bound`
  src/instance.rs
Labels: CI-skip-changelog

#5329 fix "no constructor defined" messages on PyPy
  pytests/tests/test_pyclasses.py
  src/pyclass/create_type_object.rs
Labels: CI-skip-changelog

#5355 Update free-threading docs for 0.26
  guide/src/free-threading.md
Labels: CI-skip-changelog

#5366 Use links to latest CPython stable release in docs
  Architecture.md
  guide/src/function.md
Labels: documentation, CI-skip-changelog

#5369 Clarity fixes in free-threading guide
  guide/src/free-threading.md
Labels: documentation, CI-skip-changelog

#5383 Use uv with nox
  .github/workflows/benches.yml
  .github/workflows/build.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/netlify-build.yml
  .netlify/build.sh
  pytests/noxfile.py
Labels: CI-skip-changelog
